### ISSUE TITLE
[BUG]injection_policy_tuple   value is not a valid tuple (type=type_error.tuple)

### ISSUE THREAD

**Issue by chaoyujiang** [microsoft/DeepSpeed#2602] opened 2022-12-13 09:09 UTC
**Describe the bug**

Traceback (most recent call last):
  File "./test_ds.py", line 49, in <module>
    replace_with_kernel_inject=True)
  File "/home/yjchao/venv_37/lib/python3.7/site-packages/deepspeed/__init__.py", line 311, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/yjchao/venv_37/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 121, in __init__
    config.injection_policy_tuple = injection_policy
  File "pydantic/main.py", line 385, in pydantic.main.BaseModel.__setattr__
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
injection_policy_tuple
  value is not a valid tuple (type=type_error.tuple)
[2022-12-13 17:01:34,118] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 88447

code:

model_name_or_path = '/root/model/opt/opt-13b/'
model = OPTForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.float16)

batch_size = 8
seq_length = 320
iter_num = 1
max_length = 1
in_ids = np.random.randint(low=1, high=3000, size=(batch_size, seq_length)).astype(
    np.int64
)
in_ids = torch.Tensor(in_ids).long().to(local_rank)

injection_policy={opt_transformer: module_inject.replace_policy.HFOPTLayerPolicy}
model = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=data_type,
                                 injection_policy=injection_policy,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)

**To Reproduce**
1. Simple inference script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**

(venv_37) [root@iZ2ze85vftf3u8xeax2cjkZ yjchao]# ds_report
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
async_io ............... [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
spatial_inference ...... [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/yjchao/venv_37/lib/python3.7/site-packages/torch']
torch version .................... 1.13.0+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed install path ........... ['/home/yjchao/venv_37/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.7.7+unknown, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
(venv_37) [root@iZ2ze85vftf3u8xeax2cjkZ yjchao]#

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by RezaYazdaniAminabadi** [comment] 2022-12-14 17:31
Hi @chaoyujiang,

Can you please try it without passing `injection_policy` and see if the issue is resolved?
Thanks,
Reza

**Comment by mrwyattii** [comment] 2022-12-14 22:46
@RezaYazdaniAminabadi I think the problem is with this line:
https://github.com/microsoft/DeepSpeed/blob/384f17b05bdf2c73fa6b5da66399d8c848779e89/deepspeed/inference/engine.py#L121

We expect `config.injection_policy` to be a `Dict':
https://github.com/microsoft/DeepSpeed/blob/384f17b05bdf2c73fa6b5da66399d8c848779e89/deepspeed/inference/config.py#L227

and we expect `config.injection_policy_tuple` to be a `tuple`:
https://github.com/microsoft/DeepSpeed/blob/384f17b05bdf2c73fa6b5da66399d8c848779e89/deepspeed/inference/config.py#L233

I'm not sure what the solution is, perhaps convert the dictionary to a tuple? Also I'm curious why this error isn't triggered in our [unit tests](https://github.com/microsoft/DeepSpeed/blob/384f17b05bdf2c73fa6b5da66399d8c848779e89/tests/unit/inference/test_inference.py#L362).

**Comment by RezaYazdaniAminabadi** [comment] 2022-12-15 17:45
@mrwyattii,

I think we should always ignore the policy when the `replace_with_kernel_inject` is passed as true. What do you think?

**Comment by Wenhan-Tan** [comment] 2022-12-16 02:21
I'm having the exact same issue. Do we have any temporary solutions?

**Comment by awan-10** [comment] 2023-02-14 18:32
@chaoyujiang -- please see PR #2831 for clarification about the API. 

You don't need to provide any injection_dict if you want to inject DeepSpeed kernels. Kindly remove that and just set replace_with_kernel_inject=True. You can also remove "replace_method"=auto as we will no longer need it after the linked PR gets merged.

**Closed** 2023-02-16 23:19 UTC
Labels: bug, inference
