### ISSUE TITLE
Error when using GPT2 `model.forward` method with DeepSpeed inference

### ISSUE THREAD

**Issue by Express50** [microsoft/DeepSpeed#1203] opened 2021-07-05 15:29 UTC
Hi,

I am trying to use DeepSpeed with GPT-2/Neo for inference, but encountering an error when using `model.forward` method directly. It seems that the error occurs if I don't provide an `attention_mask`.

```python
import deepspeed
from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch

tokenizer = GPT2Tokenizer.from_pretrained("gpt2-medium")
model = GPT2LMHeadModel.from_pretrained("gpt2-medium")
model = model.cuda()

model = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=torch.float,
                                 replace_method='auto')

ids = tokenizer.encode("A valley full of unicorns was discovered",
                       add_special_tokens=False, return_tensors="pt").cuda()
# attn = torch.ones((1, 8), dtype=torch.long).cuda()
output = model(
    input_ids=ids,
    # attention_mask=attn, # <-- need to provide this
    return_dict=True,
    use_cache=True
)
print(output)
```

```python
Traceback (most recent call last):
  File "deepspeed_attn.py", line 25, in <module>
    use_cache=True
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/inference/engine.py", line 222, in forward
    return self.module(*inputs, **kwargs)
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "transformers/models/gpt2/modeling_gpt2.py", line 954, in forward
    return_dict=return_dict,
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "transformers/models/gpt2/modeling_gpt2.py", line 797, in forward
    output_attentions=output_attentions,
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 611, in forward
    self.norm_b)
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 393, in forward
    self.qkv_merging)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 141, in forward
    while len(input_mask.shape) < 4:
AttributeError: 'NoneType' object has no attribute 'shape'
```

When I use `model.generate`, as in the example scripts, I am not getting any errors
as `generate` takes care of creating `attention_mask` (but in general I think `model.forward` should work even without providing `attention_mask`):

https://github.com/huggingface/transformers/blob/1ed2ebf60d87ef12bd063c7c58e484e19189c754/src/transformers/generation_utils.py#L395

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-05 16:25
Hi @Express50 

Yes, you are right. I will remove this dependency.

Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-06 18:24
Hi @Express50 

Please give this PR a try and see if the issue is resolved.
Thanks,
Reza

**Comment by Express50** [comment] 2021-07-06 20:43
Thank you for looking into this @RezaYazdaniAminabadi!

I am now getting a different error when I don't pass `attention_mask`:

```python
Traceback (most recent call last):
  File "deepspeed_attn.py", line 23, in <module>
    use_cache=True
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/inference/engine.py", line 230, in forward
    return self.module(*inputs, **kwargs)
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "transformers/models/gpt2/modeling_gpt2.py", line 954, in forward
    return_dict=return_dict,
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "transformers/models/gpt2/modeling_gpt2.py", line 797, in forward
    output_attentions=output_attentions,
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 612, in forward
    self.norm_b)
  File "torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 394, in forward
    self.qkv_merging)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 309, in forward
    output, key_layer, value_layer, context_layer = selfAttention_fp()
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 274, in selfAttention_fp
    context_layer, key_layer, value_layer = compute_attention(qkv_out)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 226, in compute_attention
    no_masking)
TypeError: softmax_context_fp32(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: int, arg7: float, arg8: bool, arg9: bool, arg10: bool, arg11: int, arg12: bool) -> List[at::Tensor]

Invoked with: tensor([[[ ... ]]],
       device='cuda:0'), tensor([[[ ... ]]],
       device='cuda:0'), tensor([0.]), None, tensor([[[ ... ]]],
       device='cuda:0'), tensor([1.7440e+28]), 16, 0.35355339059327373, False, True, False, 1, True
```

Seems that arg3 is still expecting a tensor but getting None?

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-06 20:51
Yes, you are right! I just pushed a fix, can you try again?

**Comment by Express50** [comment] 2021-07-06 21:09
@RezaYazdaniAminabadi I am now getting:
```python
...
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 312, in forward
    output, key_layer, value_layer, context_layer = selfAttention_fp()
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 277, in selfAttention_fp
    context_layer, key_layer, value_layer = compute_attention(qkv_out)
  File "deepspeed/ops/transformer/inference/transformer_inference.py", line 210, in compute_attention
    if input_mask is None:
UnboundLocalError: local variable 'input_mask' referenced before assignment
```

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-06 21:17
weird! __input_mask__ is passed as an argument [here](https://github.com/microsoft/DeepSpeed/blob/65f1fe82bb1ca3930c7852468fe82577775baf9a/deepspeed/ops/transformer/inference/transformer_inference.py#L118)! 
Let me do some more tests. So, to repro what you are seeing, I have to just remove the mask from the inputs in the huggingface example, right?

**Comment by Express50** [comment] 2021-07-06 21:24
The latest error actually happens regardless if I provide `attention_mask`.

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-06 21:25
I see. I will fix it soon. 
Thanks for trying it out 👍

**Comment by RezaYazdaniAminabadi** [comment] 2021-07-06 22:15
I retested it w/wo mask and it works for me. Can you give it a try?

**Comment by Express50** [comment] 2021-07-07 17:30
Thanks! Just tested it on my end as well and it works both with and without `attention_mask`.

**Closed** 2021-07-08 21:06 UTC
