### ISSUE TITLE
DeepSpace Interface[BUG]

### ISSUE THREAD

**Issue by Oxi84** [microsoft/DeepSpeed#2246] opened 2022-08-22 16:15 UTC
I tried this example as in tutorial page https://www.deepspeed.ai/tutorials/inference-tutorial/.  Only the one for T5 does not work, other examples for examples one for GPT-neo 125M does work nicely and give a 2+x speedup, and it makes a bit of eerors but this is a a small model:

     # create the model
     import transformers
     from transformers.models.t5.modeling_t5 import T5Block
     from transformers import pipeline
     import deepspeed
     import torch

     import os
     local_rank = int(os.getenv('LOCAL_RANK', '0'))
     world_size = int(os.getenv('WORLD_SIZE', '1'))

     pipe = pipeline("text2text-generation", model="google/t5-v1_1-small", device=local_rank)
     # Initialize the DeepSpeed-Inference engine
     pipe.model = deepspeed.init_inference(
         pipe.model,
         mp_size=world_size,
         dtype=torch.float,
         injection_policy={T5Block: ('SelfAttention.o', 'EncDecAttention.o', 'DenseReluDense.wo')}
     )
    output = pipe('Input String')

But then i get error:

    TypeError: empty() received an invalid combination of arguments - got (Parameter, device=int, dtype=NoneType), but expected one of:
     * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
     * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by RezaYazdaniAminabadi** [comment] 2022-08-22 16:35
Hi @Oxi84,

Can you please confirm if you are using the master branch? If not, can I ask which DeepSpeed version you are using?
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment] 2022-08-22 17:25
@Oxi84, could you please try this PR and see if the issue is fixed?
Thanks.

**Comment by Oxi84** [comment] 2022-08-22 17:31
Hello, thanks for answer, what do you by master branch?
I have just installed using: 
pip install deepspeed.

Regards

**Comment by Oxi84** [comment] 2022-08-22 17:42
I checked version is: 0.7.0

It does not for for T5 on rtx 3060 as well, cuda 11.3

**Comment by RezaYazdaniAminabadi** [comment] 2022-08-22 17:54
@Oxi84, please check out the the branch on this [PR ](https://github.com/microsoft/DeepSpeed/pull/2247) and install it deepspeed from source using `pip install -e .` and if it fixes the issue it will be merged into the newer version of DeepSpeed that you can use noramlly by doing `pip install deepspeed`.
Thanks,
Reza

**Comment by Oxi84** [comment] 2022-08-22 18:51
I will try to find how to do it. Because I am  using it in jypiter notebook

**Comment by Oxi84** [comment] 2022-08-22 19:05
Is this correct?
!pip install --quiet git+https://github.com/microsoft/DeepSpeed.git

**Comment by mrwyattii** [comment] 2022-08-22 19:17
@Oxi84 that will install the master branch. If you want to install the PR branch that @RezaYazdaniAminabadi linked to, do this:
`!pip install --quiet git+https://github.com/microsoft/DeepSpeed@ds-inference/fix-wo-policy`

**Comment by Oxi84** [comment] 2022-08-22 19:24
> 

After doing this i get the error:

    /opt/conda/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py in _replace(child, name, conv_linear_layer)
    659                         new_bias.data.copy_(child.bias.data)
    660                 else:
--> 661                     new_bias.data.copy_(child.bias.data)
    662                 return LinearAllreduce(data, child.bias if child.bias is None else \
    663                             torch.nn.parameter.Parameter(new_bias.to(torch.cuda.current_device())), mp_group)

    AttributeError: 'NoneType' object has no attribute 'data

**Comment by Oxi84** [comment] 2022-08-22 19:59
For T5-large it is around 20% faster. This code does in 0.65 seconds while  via pytorch it is around 0.8 seconds

**Comment by jeffra** [comment] 2022-08-23 21:45
Please re-open if #2247 doesn't address your issue

**Closed by jeffra** 2022-08-23 21:45 UTC
Labels: bug
