### ISSUE TITLE
Loss computation is wrong when gradient_accumulation_steps > 1

### ISSUE THREAD

**Issue by rfernand2** [microsoft/DeepSpeed#1107] opened 2021-05-26 11:31 UTC
I am pretraining a Roberta model using HuggingFace Transformer and DeepSpeed.  The loss being displayed on the console seems to be the true loss divided by the gradient_accumulation_steps.  Here a few runs with different accum values that show the problem:

<p style="margin:0in;font-family:Calibri;font-size:11.0pt">

<div style="direction:ltr">

| batch_size | batch_size_per_gpu | gradient_accumulation_steps | V100-32gb | samples/sec | loss | steps
 -- | -- | -- | -- | -- | -- | --
 64 | 64 | 1 | 8x | 516 | 3.9951 | 50000
 512 | 64 | 8 | 8x | 1376 | .6865 | 50000
 4096 | 64 | 64 | 8X | 1845 | .0989 | 50000
 16384 | 64 | 256 | 8X | 1900 | .0300 | 50000

</div>

**Comment by tjruwase** [comment] 2021-05-26 17:55
@rfernand2, can you please share a screenshot to help decide whether the print is coming from HF or DeepSpeed. 

Also, besides the console printout, are you seeing any convergence issues in the model?

**Comment by rfernand2** [comment] 2021-05-26 22:54
Hi @tjruwase,

Good question.  The only loss I see on the console is from HF:

![image](https://user-images.githubusercontent.com/4296158/119741349-5fd35c80-be3a-11eb-8a2d-6f56f1ce122c.png)

**Note**: my app updates some of the HF "logs" dict on the on_log callback, but doesn't touch the "loss" entry.

**Comment by tjruwase** [comment] 2021-05-26 23:10
@rfernand2, thanks for the clarification.  Perhaps the HF folks have documentation on expectations of logged loss values with gradient accumulation steps > 1, I am not sure.

**Comment by rfernand2** [comment] 2021-05-27 01:16
@tjruwase, does deepspeed participate in the calculation of the loss?  Is there a HF person we can include in this conversation who might be able to respond?  Thanks.

**Comment by tjruwase** [comment] 2021-05-27 13:57
Yes, deepspeed calls the model's foward method to compute loss. However, deepspeed returns an unscaled loss value to the client as seen [here](https://github.com/microsoft/DeepSpeed/blob/d2cf66a66847aa7f8d25da5708b7016e54f29e0a/deepspeed/runtime/engine.py#L1086) and [here](https://github.com/microsoft/DeepSpeed/blob/d2cf66a66847aa7f8d25da5708b7016e54f29e0a/deepspeed/runtime/engine.py#L1113). 

@stas00, do you have any thoughts on this?

**Comment by stas00** [comment] 2021-05-27 16:23
1. non-deepspeed transformers calculates loss:
```
loss = loss / self.args.gradient_accumulation_steps
```
as you can see here:
https://github.com/huggingface/transformers/blob/80d712fac6ccae308a2f408ebbc0c4d8c482d509/src/transformers/trainer.py#L1743-L1745

2. for deepspeed I skipped this step since I discovered that deepspeed was already doing that.

https://github.com/microsoft/DeepSpeed/blob/d2cf66a66847aa7f8d25da5708b7016e54f29e0a/deepspeed/runtime/engine.py#L1141-L1143

This contradicts what @tjruwase says though.

**Comment by tjruwase** [comment] 2021-05-27 16:59
@stas00, thanks for chiming in. 

So I think the issue is that scaled loss, rather than unscaled, is printed in the console. I don't there is any convergence problems. Also, the deepspeed code that you reference is in backward(), while I was referring to foward() returning unscaled loss.  So you are correct that backward() returns scaled loss. So the question is what is printed on the console, output of forward() or backward()? I am not sure how to figure that out.

**Comment by stas00** [comment] 2021-05-27 17:24
Here is the full logic:

```
        if self.args.gradient_accumulation_steps > 1 and not self.deepspeed:
            # deepspeed handles loss scaling by gradient_accumulation_steps in its `backward`
            loss = loss / self.args.gradient_accumulation_steps

        if self.use_amp:
            self.scaler.scale(loss).backward()
        elif self.use_apex:
            with amp.scale_loss(loss, self.optimizer) as scaled_loss:
                scaled_loss.backward()
        elif self.deepspeed:
            # loss gets scaled under gradient_accumulation_steps in deepspeed
            loss = self.deepspeed.backward(loss)
        else:
            loss.backward()
```

So in non-DS case, 
1. `loss` is the output of forward
2. it gets scaled
3. backward is called on this value
4. this is the reported `loss`, which is scaled

In DS case:
1. `loss` is the output of forward
2. it doesn't gets scaled by HF Trainer
3. DS backward is called on this value, which scales the loss
4. the updated `loss` is now scaled too
4. the reported `loss` is a scaled loss

**Comment by tjruwase** [comment] 2021-05-27 17:47
@stas00, awesome that explains the mystery. Thanks.

@rfernand2, hope this helps.

**Comment by stas00** [comment] 2021-05-27 17:50
If this needs to be documented please let me know - always happy to improve the docs.

**Comment by rfernand2** [comment] 2021-05-27 18:37
@stas00, @tjruwase - thanks, but are we in agreement on the loss value being reported in the console (and as logged to tensorboard) by the HF trainer should be the true loss for the model (unaffected by the gradient accumulation steps, or any other side effects of how the training was done)?

**Comment by tjruwase** [comment] 2021-05-27 18:57
@rfernand2, I agree with that in the sense that reported loss should be the output of forward(). 

Now, I don't even remember why deepspeed returns anything on backward(). From the HF logic shared by stas, only deepspeed returns loss on backward. So deepspeed requires one of these two changes: 
  (1) backward() returns nothing, which will require a change in HF, or 
  (2) backward() returns unscaled loss (i.e., the input), which requires no change in HF

**Comment by stas00** [comment] 2021-05-27 19:08
`training_step` in `trainer.py` returns the same `loss` w/ or w/o Deepspeed. I had to workaround deepspeed's way to match Trainer's behavior. So things are consistent here and require no changes from Deepspeed.

I think what you're suggesting @rfernand2 is that you think that Trainer should be reporting the total accumulated loss and not per step. Please raise this issue at https://github.com/huggingface/transformers/issues

If Trainer changes to report the total accumulated loss we can easily adapt the deepspeed case to match.

**Comment by rfernand2** [comment] 2021-05-27 19:30
@stas00 - my definition of loss is always the **mean** of the loss for the samples computed over.  This way it has a consistent scale, independent of the number of workers used to compute it (one just takes the mean of each worker's mean loss).  For a given model and dataset, ML experimenter's can learn expected loss values (baseline losses, training curves, etc.) that don't need to vary with the distributed learning details of the training.  In other words, I expect the report loss to always be on the same scale as the loss reported by a single GPU (on a single node).  Does that make sense?

**Comment by stas00** [comment] 2021-05-27 19:42
I spent some time reading through `trainer.py` and it does handle the scale across gpus as you are suggesting, but for some reason chooses to scale it by gradient accum steps. Perhaps it's compensating for some other place where it's scaled up and I'm missing it?

@sgugger, would you please have a few minutes to have a look at this? Thank you!

**Comment by sgugger** [comment] 2021-05-27 20:02
I am not familiar with the logic of deepspeed, but outside of deespeed, the loss printed by the HF Trainer stays in the same range for all kinds of values of gradient accumulation steps:
```
python examples/pytorch/text-classification/run_glue.py --model_name_or_path bert-base-cased --task mrpc --logging_step 10 --do_train --output_dir ~/tmp/tst-glue --num_train_epochs 1 --overwrite_output_dir --gradient_accumulation_step xxx
```
for various values of xxx and the first log shows a loss between 0.7 and 0.8.

Since we sum `gradient_accumulation_steps` losses before doing the optimizer step, the true loss needs to be divided once by `gradient_accumulation_steps` otherwise it will be `gradient_accumulation_steps` too big (and the gradients as well).

**Comment by stas00** [comment] 2021-05-27 23:37
OK, so I need to sit with debugger a bit and see if something is off here - it appears that perhaps deepspeed's "branch" gets scaled by the gradient accum steps twice according to the comments. So it calls for an investigation.

I will have time to look next week, unless someone beats me to it.

@rfernand2, if you don't hear from me by Tue please kindly ping me. This is high priority, but I'm swamped for the next 2 days.

**Comment by rfernand2** [comment] 2021-05-28 00:50
@stas00 - thanks, that sounds great!  Would it still be helpful for me to open this issue under HF Transformers, as suggested above?

**Comment by stas00** [comment] 2021-05-28 01:30
This is probably a good idea. Thank you, @rfernand2!

Once I get a chance to understand where the problem comes from we can see which side (or both?) need fixing.

**Comment by rfernand2** [comment] 2021-05-28 05:55
See Also: https://github.com/huggingface/transformers/issues/11919

**Comment by tjruwase** [comment] 2021-05-29 14:38
@stas00, the fix should involve ignoring the return value of `deepspeed.backward()` in this [line](https://github.com/huggingface/transformers/blob/8d171628fe84bdf92ee40b5375d7265278180f14/src/transformers/trainer.py#L1754). Or at least not updating loss with this return value since it is the scaled loss value, similar to `scaled_loss`  in this [line](https://github.com/huggingface/transformers/blob/8d171628fe84bdf92ee40b5375d7265278180f14/src/transformers/trainer.py#L1750)

I will add this comment to the HF issue as well.

**Comment by stas00** [comment] 2021-05-29 16:25
@rfernand2, how do I reproduce your report? 

and where did you pull those numbers from?

We need 2 short reproducible examples using standard datasets with different grad accumulation settings.

If I run:

```
export BS=16; rm -r output_dir; PYTHONPATH=src USE_TF=0 CUDA_VISIBLE_DEVICES=0 deepspeed --num_gpus=1 examples/pytorch/translation/run_translation.py --model_name_or_path t5-small --output_dir output_dir --adam_eps 1e-06 --do_train   --label_smoothing 0.1 --learning_rate 3e-5 --logging_first_step --logging_steps 1 --max_source_length 128 --max_target_length 128 --num_train_epochs 1 --overwrite_output_dir --per_device_eval_batch_size $BS --per_device_train_batch_size $BS --predict_with_generate --eval_steps 2500 --sortish_sampler --source_lang en --target_lang ro --dataset_name wmt16 --dataset_config "ro-en" --source_prefix "translate English to Romanian: " --val_max_target_length 128 --warmup_steps 50 --max_train_samples 128 --deepspeed tests/deepspeed/ds_config_zero3.json
```

vs:

```
export BS=1;rm -r output_dir; PYTHONPATH=src USE_TF=0 CUDA_VISIBLE_DEVICES=0 deepspeed --num_gpus=1 examples/pytorch/translation/run_translation.py --model_name_or_path t5-small --output_dir output_dir --adam_eps 1e-06 --do_train   --label_smoothing 0.1 --learning_rate 3e-5 --logging_first_step --logging_steps 1 --max_source_length 128 --max_target_length 128 --num_train_epochs 1 --overwrite_output_dir --per_device_eval_batch_size $BS --per_device_train_batch_size $BS --predict_with_generate --eval_steps 2500 --sortish_sampler --source_lang en --target_lang ro --dataset_name wmt16 --dataset_config "ro-en" --source_prefix "translate English to Romanian: " --val_max_target_length 128 --warmup_steps 50 --max_train_samples 128 --gradient_accumulation_steps=16 --deepspeed tests/deepspeed/ds_config_zero3.json
```

I get the same scale reported in both cases. So I struggle to understand the discrepancy you have reported.

You can tweak my examples to show me what you're talking about it.

The first example prints:

```
{'loss': 3.0593, 'learning_rate': 0.0, 'epoch': 0.12}
{'loss': 3.0766, 'learning_rate': 5.315514604066738e-06, 'epoch': 0.25}
{'loss': 3.1975, 'learning_rate': 8.424891319481444e-06, 'epoch': 0.38}
{'loss': 2.9145, 'learning_rate': 1.0631029208133476e-05, 'epoch': 0.5}
{'loss': 3.2021, 'learning_rate': 1.2342242697966633e-05, 'epoch': 0.62}
{'loss': 2.9113, 'learning_rate': 1.3740405923548181e-05, 'epoch': 0.75}
{'loss': 2.8865, 'learning_rate': 1.4922536086995832e-05, 'epoch': 0.88}
{'loss': 3.1581, 'learning_rate': 1.594654381220021e-05, 'epoch': 1.0}
```

The second example prints:

```
{'loss': 3.0082, 'learning_rate': 0.0, 'epoch': 0.12}
{'loss': 2.9949, 'learning_rate': 5.315514604066738e-06, 'epoch': 0.25}
{'loss': 2.9685, 'learning_rate': 8.424891319481444e-06, 'epoch': 0.38}
{'loss': 2.883, 'learning_rate': 1.0631029208133476e-05, 'epoch': 0.5}
{'loss': 3.0431, 'learning_rate': 1.2342242697966633e-05, 'epoch': 0.62}
{'loss': 2.8464, 'learning_rate': 1.3740405923548181e-05, 'epoch': 0.75}
{'loss': 2.9141, 'learning_rate': 1.4922536086995832e-05, 'epoch': 0.88}
{'loss': 3.0492, 'learning_rate': 1.594654381220021e-05, 'epoch': 1.0}
```

As you can see no problem with scale.

I did the same w/o deepspeed and get the same results.

**Comment by rfernand2** [comment] 2021-05-29 18:28
@stas00: I used my own script (about 300 lines), which calls the HT trainer specifying a deepspeed config file.   Let me see if I can find a smaller failing test case (from my script or your shell command).

**Comment by stas00** [comment] 2021-05-29 18:30
And while you're at, please try removing deepspeed and first check that the Trainer alone gives you the expected results.

**Comment by rfernand2** [comment] 2021-05-29 18:31
@stas00: in the meantime, have you tried your script with "bs=16 grad_acc=16"?  That way, only the grad_acc is being changed between your comparisons.

**Comment by stas00** [comment] 2021-05-29 18:38
"bs=1 grad_acc=16" is the same as "bs=16 grad_acc=1": the "total_bs=16"

what would you like me to compare "bs=16 grad_acc=16" to? Here you have the "total bs=256"

Let's find a baseline we agree on and then do variations and check that the behavior is consistent (or not).

It should be easy for your to run those examples, since they require no coding - and the training args are the same as you pass them to the trainer.

Feel free to use another example that perhaps is closer to what you're trying to do.

That would be far easier than trying to figure out your custom script I believe.

**Comment by rfernand2** [comment] 2021-05-29 20:45
@stas00, I am pursuing 2 parallel tracks: trying to shrink my test case and trying to get your big cmd line to fail.  I don't have a standalone Linux box with deepspeed requirements properly installed, so I am submitting all my jobs thru Azure ML (so turnaround is slower than ideal).

Here is the output from 3 runs of my latest test case script (where I specify the **gradient_accumulation_steps**  ONLY  in the DeepSpeed config file, not in the training_args for Trainer, in case that makes a difference):

   **gradient_accumulation_steps = 8**
```
2021-05-29 19:53:27 run6222: Loading extension module utils...
2021-05-29 19:53:27 run6222: Time to load utils op: 22.438228845596313 seconds
2021-05-29 19:53:45 run6222: [2021-05-29 19:53:43,103] [INFO] [timer.py:157:stop] 0/100, SamplesPerSec=1166.1363801104596
2021-05-29 19:53:54 run6222: [2021-05-29 19:53:51,402] [INFO] [timer.py:157:stop] 0/200, SamplesPerSec=1267.2124274900398
2021-05-29 19:54:00 run6222: [2021-05-29 19:53:59,614] [INFO] [timer.py:157:stop] 0/300, SamplesPerSec=1310.1800310403655
2021-05-29 19:54:09 run6222: [2021-05-29 19:54:07,901] [INFO] [timer.py:157:stop] 0/400, SamplesPerSec=1330.1747588829498
2021-05-29 19:54:18 run6222: [2021-05-29 19:54:16,237] [INFO] [timer.py:157:stop] 0/500, SamplesPerSec=1340.0907121181817
2021-05-29 19:54:18 run6222: {'loss': 1.1228, 'learning_rate': 4.99973190742677e-05, 'epoch': 0.0}
2021-05-29 19:54:27 run6222: [2021-05-29 19:54:24,647] [INFO] [timer.py:157:stop] 0/600, SamplesPerSec=1344.5355834219233
```
   **gradient_accumulation_steps = 32**
```
2021-05-29 20:08:59 run6224: Loading extension module utils...
2021-05-29 20:08:59 run6224: Time to load utils op: 21.426029682159424 seconds
2021-05-29 20:09:17 run6224: [2021-05-29 20:09:15,718] [INFO] [timer.py:157:stop] 0/100, SamplesPerSec=1301.9975041645923
2021-05-29 20:09:23 run6224: [2021-05-29 20:09:23,285] [INFO] [timer.py:157:stop] 0/200, SamplesPerSec=1421.7146767692252
2021-05-29 20:09:32 run6224: [2021-05-29 20:09:30,876] [INFO] [timer.py:157:stop] 0/300, SamplesPerSec=1463.2821617259383
2021-05-29 20:09:41 run6224: [2021-05-29 20:09:38,503] [INFO] [timer.py:157:stop] 0/400, SamplesPerSec=1481.550576935915
2021-05-29 20:09:47 run6224: [2021-05-29 20:09:46,087] [INFO] [timer.py:157:stop] 0/500, SamplesPerSec=1494.535188949007
2021-05-29 20:09:47 run6224: {'loss': 0.306, 'learning_rate': 4.999935138893573e-05, 'epoch': 0.0}
```
   **gradient_accumulation_steps = 1024**
```
2021-05-29 20:34:48 run6229: Loading extension module utils...
2021-05-29 20:34:48 run6229: Time to load utils op: 23.03141951560974 seconds
2021-05-29 20:35:06 run6229: [2021-05-29 20:35:05,088] [INFO] [timer.py:157:stop] 0/100, SamplesPerSec=1577.854606700266
2021-05-29 20:35:12 run6229: [2021-05-29 20:35:12,115] [INFO] [timer.py:157:stop] 0/200, SamplesPerSec=1617.3265361743984
2021-05-29 20:35:21 run6229: [2021-05-29 20:35:19,240] [INFO] [timer.py:157:stop] 0/300, SamplesPerSec=1622.518910437454
2021-05-29 20:35:27 run6229: [2021-05-29 20:35:26,261] [INFO] [timer.py:157:stop] 0/400, SamplesPerSec=1629.9639464586596
2021-05-29 20:35:33 run6229: [2021-05-29 20:35:33,425] [INFO] [timer.py:157:stop] 0/500, SamplesPerSec=1628.719015606329
2021-05-29 20:35:33 run6229: {'loss': 0.0102, 'learning_rate': 5e-05, 'epoch': 0.0}
2021-05-29 20:35:42 run6229: [2021-05-29 20:35:40,578] [INFO] [timer.py:157:stop] 0/600, SamplesPerSec=1628.090819119872
2021-05-29 20:35:48 run6229: [2021-05-29 20:35:47,621] [INFO] [timer.py:157:stop] 0/700, SamplesPerSec=1633.2896287195729
2021-05-29 20:35:57 run6229: [2021-05-29 20:35:55,203] [INFO] [timer.py:157:stop] 0/800, SamplesPerSec=1617.5132990767802
2021-05-29 20:36:03 run6229: [2021-05-29 20:36:02,196] [INFO] [timer.py:157:stop] 0/900, SamplesPerSec=1622.9195991805655
2021-05-29 20:36:09 run6229: [2021-05-29 20:36:09,721] [INFO] [timer.py:157:stop] 0/1000, SamplesPerSec=1614.1177976496538
2021-05-29 20:36:09 run6229: {'loss': 0.0102, 'learning_rate': 5e-05, 'epoch': 0.0}
```
I should also mention that my current script specifies the **train_micro_batch_size_per_gpu** in the DeepSpeed config file AND specifies **per_device_train_batch_size** in the TrainingArgs to Trainer, in case that makes a difference.

**Comment by rfernand2** [comment] 2021-05-29 21:48
Here's one more interesting run from my test case:
**gradient_accumulation_steps = 1**
```
2021-05-29 21:06:27 run6231: Loading extension module utils...
2021-05-29 21:06:27 run6231: Time to load utils op: 22.439236879348755 seconds
2021-05-29 21:06:36 run6231: [2021-05-29 21:06:33,240] [INFO] [unfused_optimizer.py:246:_update_scale] Grad overflow on iteration: 0
2021-05-29 21:06:36 run6231: [2021-05-29 21:06:33,241] [INFO] [unfused_optimizer.py:248:_update_scale] Reducing dynamic loss scale from 65536 to 32768.0
2021-05-29 21:06:36 run6231: [2021-05-29 21:06:33,241] [INFO] [unfused_optimizer.py:174:step] [deepspeed] fp16 dynamic loss scale overflow! Skipping step. Attempted loss scale: 65536, reducing to 32768.0
2021-05-29 21:06:51 run6231: [2021-05-29 21:06:49,574] [INFO] [logging.py:60:log_dist] [Rank 0] step=100, skipped=1, lr=[4.999571916697584e-05, 4.999571916697584e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:06:51 run6231: [2021-05-29 21:06:49,575] [INFO] [timer.py:157:stop] 0/100, SamplesPerSec=626.1667355513339
2021-05-29 21:07:06 run6231: [2021-05-29 21:07:04,836] [INFO] [logging.py:60:log_dist] [Rank 0] step=200, skipped=1, lr=[4.999139509321406e-05, 4.999139509321406e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:07:06 run6231: [2021-05-29 21:07:04,836] [INFO] [timer.py:157:stop] 0/200, SamplesPerSec=651.5778648135631
2021-05-29 21:07:21 run6231: [2021-05-29 21:07:20,415] [INFO] [logging.py:60:log_dist] [Rank 0] step=300, skipped=1, lr=[4.998707101945228e-05, 4.998707101945228e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:07:21 run6231: [2021-05-29 21:07:20,416] [INFO] [timer.py:157:stop] 0/300, SamplesPerSec=656.2537307896692
2021-05-29 21:07:39 run6231: [2021-05-29 21:07:37,549] [INFO] [logging.py:60:log_dist] [Rank 0] step=400, skipped=1, lr=[4.99827469456905e-05, 4.99827469456905e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:07:39 run6231: [2021-05-29 21:07:37,549] [INFO] [timer.py:157:stop] 0/400, SamplesPerSec=641.742366248221
2021-05-29 21:07:54 run6231: [2021-05-29 21:07:53,366] [INFO] [logging.py:60:log_dist] [Rank 0] step=500, skipped=1, lr=[4.997842287192872e-05, 4.997842287192872e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:07:54 run6231: [2021-05-29 21:07:53,366] [INFO] [timer.py:157:stop] 0/500, SamplesPerSec=644.6128644196789
2021-05-29 21:07:54 run6231: {'loss': 6.8016, 'learning_rate': 4.997842287192872e-05, 'epoch': 0.0}
2021-05-29 21:08:09 run6231: [2021-05-29 21:08:09,073] [INFO] [logging.py:60:log_dist] [Rank 0] step=600, skipped=1, lr=[4.997409879816694e-05, 4.997409879816694e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
2021-05-29 21:08:09 run6231: [2021-05-29 21:08:09,073] [INFO] [timer.py:157:stop] 0/600, SamplesPerSec=647.2722155336394
```
Compare this to the above run (**gradient_accumulation_steps**=1024):  **loss** here is "6.8" (vs. .0102 above) and **SamplesPerSec** is 647 (vs. 1614 above).  Looks like **SamplesPerSec** might also be getting scaled.

I'm doing the "without DeepSpeed" tests now...

**Comment by rfernand2** [comment] 2021-05-30 00:29
@stas00: OK, some results.  When I run **without** DeepSpeed, I am forced to specify both **per_device_train_batch_size** and **gradient_accumulation_steps** thru the TrainingArgs.  When I do that, I see **no loss scaling** (comparing gas=1 and gas=32).  I also see each log msg taking much longer to be produced - it seems as though the gas value is all of the sudden being recognized and applied (vs. specifying gas only in the DeepSpeed config file).

Is it possible that when **gradient_accumulation_steps** is only specified thru the DS config file, it is not applied (because it is not specified in the TrainingArgs) BUT it is used in scaling the loss (as if it were applied)?  Maybe something similar for the scaling of the SamplesPerStep.  What do you think?

**Comment by stas00** [comment] 2021-05-30 02:04
> Is it possible that when gradient_accumulation_steps is only specified thru the DS config file, it is not applied (because it is not specified in the TrainingArgs

That is correct. That's why you should either use `auto` for ds config values or making sure you sync trainer args and ds config yourself.

Let me know how I can make it more loud-n-clear:  https://huggingface.co/transformers/master/main_classes/trainer.html#shared-configuration.

Originally, I tried to overwrite ds config, but then people were getting confused, so now there is no more overwriting. And the `auto` setting is there precisely so that one doesn't have to think twice and there is no place for an error.

**Comment by stas00** [comment] 2021-06-01 20:30
update: Note to myself - need to write fp16 test. Hoping to get to it today/tomorrow.

**Comment by rfernand2** [comment] 2021-06-01 20:42
@stas00, I now understand the issue I ran into and have some suggestions for how to minimize for future; will write-up and include here later today...

**Comment by rfernand2** [comment] 2021-06-01 22:48
OK, I can confirm that the incorrect **loss** and **SamplesPerSec** console values I saw before are now correct, when I sync my **gradient_accumulation_steps** and **device batch size** for both the HF TrainerArgs and the DS config dictionary (I replaced my config files with a config dictionary that I can keep in-sync programatically).  

Regarding the [HF webpage](https://huggingface.co/transformers/master/main_classes/trainer.html#shared-configuration) that covers these issues, I have only ever read the top 1/2 of that page, which covers the TrainingArgs parameters.  The bottom 1/2 is full of great information - I suggest you make it into its own standalone web page that is liked to by the original page.  I think this will make it more discoverable and more likely to be read on discovery.

When I first came across the overlapping parameters (HF/DS) being set in 2 places, from my long experience as a programmer, I assumed that the DS config file would overwrite the HF-specified parameters

**Comment by stas00** [comment] 2021-06-01 23:11
I'm glad to hear you sorted out the problem, @rfernand2 

1. I'm in the process of splitting Deepspeed docs into its own doc - especially since we have just merged a commit that decouples deepspeedconfig from the Trainer.

2. I'm not sure what to do about the duplicity of the shared config attributes. 

My first take was to overwrite automatically any config values in ds config to match trainer args. But that wasn't a happy results, as users were getting confused - they would enter a value in ds config and would get it overwritten (who reads the logs that said that it was overwritten).

Then I came up with the `auto` value which flagged to the user that let the trainer figure it out.

Clearly this is not enough. And I should probably check that if ds_config entry is not auto - that it matches trainer value for the same config option.  Just need to choose whether to assert whether the values mismatch or warn (but as I repeat in many places warnings are a very inefficient way to flag something when they are lost in the sea of warnings).

Perhaps I should try to assert and if it makes no sense to change to log.warn. Not sure. Need to contemplate this.

**Comment by stas00** [comment] 2021-06-01 23:17
re: linking from deepspeed to HF, just give me a day - I'm moving docs to a new file

**Comment by stas00** [comment] 2021-06-02 19:12
OK, Deepspeed docs now has its own home: https://huggingface.co/transformers/master/main_classes/deepspeed.html

Suggestions to improvements are very welcome.

**Comment by stas00** [comment] 2021-06-02 19:33
Oh, and we can't rely on ds config values as master over trainer args, because trainer needs them sooner than when ds config is parsed. So the best we can do is to assert if there is a mismatch.

**Comment by stas00** [comment] 2021-06-03 21:03
@rfernand2, beside your request to link to HF deepspeed doc, is there anything else we need to do to complete this ticket?

**Comment by rfernand2** [comment] 2021-06-03 21:28
@stas00 - thanks for moving that doc to its own page.  There is still the potential for other people running into the same  problems that I did.  I think any of the following would help minimize confusion and bugs:
   - have DS config file take priority over overlapping Trainer parameters (you can always parse the DS config file twice, if needed, right?)
   - collect a list of all duplicated HF/DS parameters, and for any where both are specified and conflict, issue a **hard erro**r
   - in the console, issue a "HF/DS parameter resolution report", showing the arg name, value, and source (for the actual value being used)
   - in the doc for the Trainer "deepspeed" parameter, mention something like "Its strongly suggested that you pass in a python dictionary (vs. config file name) so that your app can programmatically synchronize parameters passed to both HF and DS".

**Comment by stas00** [comment] 2021-06-03 21:43
Thank you for the suggestions to make things easier for users, @rfernand2 

> There is still the potential for other people running into the same problems that I did. I think any of the following would help minimize confusion and bugs:
> 
>     * have DS config file take priority over overlapping Trainer parameters (you can always parse the DS config file twice, if needed, right?)

As I tried to explain earlier - can't do that, because they could be already used before ds_config is parsed. So Trainer args have to be the master. 

Again, this is DS integration into HF Trainer and not the other way around. Usually the main system is that one that drives the configuration.

>     * collect a list of all duplicated HF/DS parameters, and for any where both are specified and conflict, issue a **hard erro**r

Working on this now.
 
>     * in the console, issue a "HF/DS parameter resolution report", showing the arg name, value, and source (for the actual value being used)

The final DS config is printed to the log.

Let's see if we can dump the Trainer args dump too, but boy it's getting noisier and noisier. Perhaps it can be done with a flag. Let me ask.
 
>     * in the doc for the Trainer "deepspeed" parameter, mention something like "Its strongly suggested that you pass in a python dictionary (vs. config file name) so that your app can programmatically synchronize parameters passed to both HF and DS".

You don't need to do it the hard way. That's what "auto" values are for. The syncing is already done for you when you use those. Try it - it's that simple.

Otherwise there is no different between passing a dict or a file.

I suppose you could create both trainer args and ds config on the fly, and then you can sync those programmatically.

**Comment by rfernand2** [comment] 2021-06-03 21:48
@stas00 - Can you parse the DeepSpeed config file / dictionary **before** you process any of the Trainer Args?

**Comment by stas00** [comment] 2021-06-03 21:55
The user can do it now, thanks to the very recent decoupling of [HfDeepSpeedConfig](https://huggingface.co/transformers/master/main_classes/deepspeed.html#hfdeepspeedconfig). 

So yes, you can pre-parse the config, read the values, and set `TrainingArgs` accordingly. (Please feel free to contribute a more concrete code recipe.)

But we can't do this by default in HF Trainer unless we modify everything and even then it won't work. You probably don't realize that some config values are unknown until `train()` was called, so ds config can't be the master here. Please see:

https://github.com/huggingface/transformers/blob/242ec31aa59b358e631d981b545fd08330584ea8/src/transformers/deepspeed.py#L168

**Comment by rfernand2** [comment] 2021-06-03 22:55
OK, I see.  Well, hard errors for conflicting parameter values would be just as good (maybe better).  Thanks @stas00  for all your work on this large issue!

**Comment by stas00** [comment] 2021-06-04 02:07
@rfernand2, please have a look https://github.com/huggingface/transformers/pull/12021

**Comment by rfernand2** [comment] 2021-06-04 16:27
Both looks good.  As far as I am concerned, this issue has been (nicely) resolved.  Thanks again @stas00.

**Comment by stas00** [comment] 2021-06-04 16:33
Awesome. Please close the issue then. Thank you!

**Closed** 2021-06-04 16:37 UTC
