### ISSUE TITLE
I meet a question about train 

### ISSUE THREAD

**Issue by kuokay** [microsoft/DeepSpeed#3307] opened 2023-04-19 08:41 UTC
<img width="1269" alt="屏幕截图 2023-04-19 163948" src="https://user-images.githubusercontent.com/60090512/233019394-aefba46f-912b-4b9d-b6b3-095a94026333.png">
<img width="1280" alt="屏幕截图 2023-04-19 164025" src="https://user-images.githubusercontent.com/60090512/233019504-93c6116d-1470-4ffe-aa2c-d16979913f81.png">

**Comment by mrwyattii** [comment] 2023-04-19 17:01
@kuokay can you please monitor the system memory and GPU memory usage when you launch the script? I'm curious if this is caused by an OOM problem. You can monitor them with `htop` and `nvidia-smi` respectively.

**Comment by kuokay** [comment] 2023-04-22 00:35
Through monitoring, I found that the memory and video memory were not exceeded. I used wsl2 for training. I don't know whether the failure is related to wsl or not



---Original---
From: "Michael ***@***.***&gt;
Date: Thu, Apr 20, 2023 01:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/DeepSpeed] I meet a question about train  (Issue#3307)




 
@kuokay can you please monitor the system memory and GPU memory usage when you launch the script? I'm curious if this is caused by an OOM problem. You can monitor them with htop and nvidia-smi respectively.

**Comment by molly-smith** [comment] 2023-05-12 18:20
Hi @kuokay, can you please provide more information about your setup?

**ds_report output**
Please run `ds_report` to give us details about your setup.

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Comment by molly-smith** [comment] 2023-05-26 18:18
Closing. Please reopen if the issues persists.

**Closed by molly-smith** 2023-05-26 18:18 UTC
Labels: bug, deepspeed-chat, step 1, reproducibility
