### ISSUE TITLE
Quantization and pruning from DeepSpeed Compression not working

### ISSUE THREAD

**Issue by PabloVD** [microsoft/DeepSpeed#2283] opened 2022-09-01 17:21 UTC
I would like to use DeepSpeed for post-training compression with CUDA, using quantization or pruning.

I'm using a pretrained ResNet as a simple example to test how DeepSpeed works, in a simple case following [this](https://github.com/microsoft/DeepSpeedExamples/blob/master/model_compression/cifar/train.py).

However, I'm not able to achieve any performance improvement at all, neither with weight quantization, activation quantization or sparse and row pruning. When using pruning, I checked that the weights are actually modified, but no gain in the performance is obtained.

Here is the full code I'm using:

```python
import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt

import deepspeed
from deepspeed.compression.compress import init_compression, redundancy_clean
import argparse

# use GPUs if available
if torch.cuda.is_available():
    print("CUDA Available")
    device = torch.device('cuda')
else:
    print('CUDA Not Available')
    device = torch.device('cpu')

# Routine to compute the inference time
def checktime(model, ndata = 500):

    timelist = []

    for i in range(ndata):

        torch.cuda.synchronize()
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)

        start.record()
        out = model(data)
        end.record()

        torch.cuda.synchronize()
        timelist.append(start.elapsed_time(end))

    timelist = timelist[30:]    # remove the first warm up calls
    timelist = np.array(timelist)
    print("Inference time [ms]. Mean: {:.1f}, Std: {:.1f}".format(timelist.mean(),timelist.std()))

    return timelist

# An instance of the ResNet model
model = torchvision.models.resnet18().to(device)
model.eval()

"""
# Check names of layers
for name, param in model.named_parameters():
    print(name)
"""

# An example input
data = torch.rand(4, 3, 224, 224, device=device)

# Compute the inference time in the standard pre-compressed model
timelist_standard = checktime(model)
# out: Inference time [ms]. Mean: 2.7, Std: 0.1

# Get arguments for DeepSpeed
parser = argparse.ArgumentParser(description='Deepspeed')
parser = deepspeed.add_config_arguments(parser)
args = parser.parse_args()
print("\n",args,"\n")
deepspeed.init_distributed()   # I think this line is not required

# Compress the model
model = init_compression(model, args.deepspeed_config)
model = redundancy_clean(model, args.deepspeed_config)
model.eval()

# Compute the inference time in the compressed model
timelist_compressed = checktime(model)
# out: Inference time [ms]. Mean: 2.7, Std: 0.1

```

And this an example of the config file (although I tried with different variants):

```json
{ 
    "compression_training": {
      "weight_quantization": {
        "shared_parameters":{
          "enabled": true,
          "quantizer_kernel": false,
          "schedule_offset": 0,
          "quantize_groups": 1,
          "quantize_verbose": true,
          "quantization_type": "asymmetric",
          "quantize_weight_in_forward": false,
          "rounding": "nearest",
          "fp16_mixed_quantize":{
            "enabled": false,
            "quantize_change_ratio": 0.001
          }
        },
        "different_groups":{
          "wq1": {
            "params": {
                "start_bits": 12, 
                "target_bits": 8,
                "quantization_period": 50
            },
            "modules": [
              "conv1",
              "conv2"
            ]
          }
        }
      }
  }
 }
```

Am I doing something wrong to apply the DeepSpeed tools for post-training compression? Am I missing something?

Thanks in advance,
Pablo.

**Comment by xiaoxiawu-microsoft** [comment] 2022-09-27 21:11
Hi, 
Thanks for your question. 
Indeed, there is somethings missing in the code. 
you need to apply  deepspeed.initialize, see this example
(https://github.com/microsoft/DeepSpeedExamples-internal/blob/staging_compression_library_v1/model_compression/cifar/train.py#L116)

The reason is that we implemented the quantization training in our deepspeed.runtime
Let us know if you have any questions :)

**Comment by PabloVD** [comment] 2022-09-28 15:21
Hi @xiaoxiawu-microsoft thanks for your answer.
I included that line in my script, but it does not provide any performance improvement yet. Following the example you mention, I included the line after `init_compression`, so I have something like this:
```python
model = init_compression(model, args.deepspeed_config)
model, _, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=model.parameters())
model = redundancy_clean(model, args.deepspeed_config)
```
Is something else missing? I understand I don't need to re-train the model to apply compression, isn't?

**Comment by yaozhewei** [comment] 2022-09-28 21:14
Hi, 

For quantization related and sparse pruning features, it will need special kernels to get the real speedup. This part has not been fully released yet. For channel pruning, you should be able to see latency reduction. Would you mind share the config you used for channel pruning?

**Comment by xiaoxiawu-microsoft** [comment] 2022-09-29 07:11
> ovide any performance i
Just to clarify here you mean accuracy, right?
For the quantization config in your example code, it means you start with 12 bit and then slowly to 8 bit after quantization_period (steps) 50. See more here: https://www.deepspeed.ai/docs/config-json/#weight-quantization

Regarding to the question " I understand I don't need to re-train the model to apply compression, isn't?"
I would recommend training the models for a few epochs to understand how the model performance.

**Comment by xiaoxiawu-microsoft** [comment] 2022-09-29 07:32
@PabloVD 
In addition to Zhewei's comment. I would like to clarify the config you share for the weight quantization here. 
```
"wq1": {
            "params": {
                "start_bits": 12, 
                "target_bits": 8,
                "quantization_period": 50
            },
            "modules": [
              "conv1",
              "conv2"
```
The quantization periods mean you train the model won't reach to 8 bits after 50 steps (starting at 12 bits.)
If you want to get 8 bits, you need to set start_bits=8.

**Comment by PabloVD** [comment] 2022-10-03 10:17
Hi, thanks for your answers. I'm trying now with channel prunning. Here is the config file that I'm using:
```json
{
    "train_batch_size" : 32,
    "train_micro_batch_size_per_gpu": 32,
    "steps_per_print": 50,
  
    "optimizer": {
      "type": "Adam",
      "params": {
        "lr": 0.001,
        "betas": [
          0.8,
          0.999
        ],
        "eps": 1e-8,
        "weight_decay": 3e-7
      }
    },

    "zero_optimization": {
      "stage": 0
    },

    "fp16":{
      "enabled": false
    },

    "gradient_clipping": 1.0,
    "prescale_gradients": true,
  
    "wall_clock_breakdown" : false,
    
    "compression_training": {
      
      "channel_pruning":{
        "shared_parameters":{
          "enabled": true,
          "schedule_offset": 0,
          "method": "topk"
        },
        "different_groups":{
          "cp1": {
            "params": { 
                "dense_ratio": 0.5
            },
            "modules": [
              "layer....conv1"
            ],
            "related_modules": [
              ["layer....conv2", "layer....bn1"]
            ]
          }
        }
      }
    }
  }
```

However, compressing in that way raises the following error:

```
Using /home/tda/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Emitting ninja build file /home/tda/.cache/torch_extensions/py38_cu116/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.20057225227355957 seconds
[2022-10-03 12:15:19,177] [INFO] [scheduler.py:155:check_channel_pruning] Channel pruning is enabled at step 0
Traceback (most recent call last):
  File "resnettest.py", line 169, in <module>
    timelist_compressed = checktime(model)
  File "resnettest.py", line 38, in checktime
    out = model(data)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/tda/.local/lib/python3.8/site-packages/torchvision/models/resnet.py", line 273, in _forward_impl
    x = self.layer1(x)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/torchvision/models/resnet.py", line 146, in forward
    out = self.conv1(x)
  File "/home/tda/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tda/.local/lib/python3.8/site-packages/deepspeed/compression/basic_layer.py", line 658, in forward
    mask = self.get_mask(pruning_type='channel')
  File "/home/tda/.local/lib/python3.8/site-packages/deepspeed/compression/basic_layer.py", line 593, in get_mask
    raise NotImplementedError
NotImplementedError

```

Do you find the source of the error from this log?
Thanks in advance,
Pablo.

**Comment by PabloVD** [comment] 2022-10-03 10:21
>  The quantization periods mean the model won't reach to 8 bits after 50 steps (starting at 12 bits.)
If you want to get 8 bits, you need to set start_bits=8.

@xiaoxiawu-microsoft thanks for the clarification. Then, I understand that the indicated `quantization_period` is irrelevant in post-training compression; it will always quantize with `start_bits`, is that right?
Thanks.

**Comment by yaozhewei** [comment] 2022-10-07 19:40
> 

Looks like the pruning method has some issue. Did you tried the CIFAR10 example here: https://github.com/microsoft/DeepSpeedExamples/blob/master/model_compression/cifar/config/ds_config_channel_prune.json? 

It would be easier if you can provide a minimal reproduce example here so we can debug it on our end.

**Comment by tjruwase** [comment] 2022-11-04 18:49
Closing for now. Please (re)open as needed.

**Closed by tjruwase** 2022-11-04 18:49 UTC
Labels: bug, compression

**Comment by ZecchinLeonardo** [comment] 2023-01-31 13:37
Hi, I was trying to compress Resnet with channel pruning to test Deepspeed just like @PabloVD was, and I stumbled upon the same issue. I have created a minimal reproducible copy of the supposed bug, the error I get is the same. I have tested that using a different model (like EfficientNet) does not cause the program to crash.
Here is the code: (dstest_minimal.py)
```
import torch
import torchvision

import deepspeed
from deepspeed.compression.compress import init_compression, redundancy_clean
import argparse

# use GPUs if available
if torch.cuda.is_available():
    print("CUDA Available")
    device = torch.device('cuda')
else:
    print('CUDA Not Available')
    device = torch.device('cpu')

# An instance of the ResNet model
model = torchvision.models.resnet18().to(device)
model.eval()

# An example input
data = torch.rand(4, 3, 224, 224).to(device)
#data = data.type(torch.cuda.FloatTensor)

#this works
out = model(data)

# Get arguments for DeepSpeed
parser = argparse.ArgumentParser(description='Deepspeed')
parser = deepspeed.add_config_arguments(parser)
args = parser.parse_args()

# Compress the model
model = init_compression(model, args.deepspeed_config)
model, _, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=model.parameters())
model = redundancy_clean(model, args.deepspeed_config)
model.eval()
model.to(device)

#this doesn't work
out = model(data)
```

This is the config file: (config_minimal.json)
```
{
    "train_batch_size" : 32,
    "train_micro_batch_size_per_gpu": 32,
    "steps_per_print": 50,
    
    "optimizer": {
        "type": "Adam",
        "params": {
          "lr": 0.001,
          "betas": [
            0.8,
            0.999
          ],
          "eps": 1e-8,
          "weight_decay": 3e-7
        }
      },
    
  
    "compression_training": {
      "channel_pruning":{
        "shared_parameters":{
          "enabled": true,
          "schedule_offset": 0,
          "method": "topk"
        },
        "different_groups":{
          "cp1": {
            "params": { 
                "dense_ratio": 0.5
            },
            "modules": [
              "layer....conv1"
            ],
            "related_modules": [
              ["layer....conv2", "layer....bn2"]
            ]
          }
        }
      }
    }
  }
```
and this is the .sh file: (run_minimal.sh)
```
#!/bin/bash
python dstest_minimal.py --deepspeed --deepspeed_config config_minimal.json
```
Finally, the error:
```
Traceback (most recent call last):
  File "dstest_minimal.py", line 45, in <module>
    out = model(data)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1836, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torchvision/models/resnet.py", line 273, in _forward_impl
    x = self.layer1(x)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torchvision/models/resnet.py", line 92, in forward
    out = self.conv1(x)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/deepspeed/compression/basic_layer.py", line 660, in forward
    mask = self.get_mask(pruning_type='channel')
  File "/home/leonardo/leo_stuff/lib/python3.8/site-packages/deepspeed/compression/basic_layer.py", line 593, in get_mask
    raise NotImplementedError
NotImplementedError
```
Thank you for your time.
