### ISSUE TITLE
RuntimeError: Special sequence length found in softmax backward [BUG]

### ISSUE THREAD

**Issue by FarzanT** [microsoft/DeepSpeed#2636] opened 2022-12-21 00:36 UTC
**Describe the bug**
DeepSpeedTransformerLayer seems to be not compatible with sequence lengths larger than 2048, because of `launch_attn_softmax_backward_v2` here:
https://github.com/microsoft/DeepSpeed/blob/7bcb4fabeb6c2a84998ab41af62bd0cc9eb25f2e/csrc/transformer/softmax_kernels.cu#L551-L582

I have created a transformer-based model that has a fixed input sequence length of 12896. The model works ok with a custom transformer module written in PyTorch, and I have also integrated it with DeepSpeed Distributed Training in PyTorch Lightning, with FP16 precision.
I copied the exact model, but replaced the transformer layers with the transformer kernel described in the **very brief** example provided in the tutorials: https://www.deepspeed.ai/tutorials/transformer_kernel/
However, the model throws different errors based on whether I use a mask or not.
Please see below for the full stack trace.

**To Reproduce**

Here's a relatively small example to reproduce the problem. (please let me know if I'm using the transformer kernel incorrectly!):
```python
import copy
import torch
from deepspeed import DeepSpeedTransformerConfig, DeepSpeedTransformerLayer
from torch import nn


class DeepSpeedTransformerEncoder(nn.Module):
    def __init__(self, **ds_config):
        super().__init__()
        config = DeepSpeedTransformerConfig(batch_size=ds_config['batch_size'],
                                            hidden_size=ds_config['hidden_size'],
                                            heads=ds_config['heads'],
                                            attn_dropout_ratio=0.0,
                                            hidden_dropout_ratio=ds_config['hidden_dropout_ratio'],
                                            num_hidden_layers=ds_config['num_hidden_layers'],
                                            initializer_range=0.02,
                                            seed=ds_config['seed'],
                                            fp16=ds_config['fp16'],
                                            pre_layer_norm=ds_config['pre_layer_norm'],
                                            attn_dropout_checkpoint=ds_config['attn_dropout_checkpoint'],
                                            normalize_invertible=ds_config['normalize_invertible'],
                                            gelu_checkpoint=ds_config['gelu_checkpoint'])

        self.layers = nn.ModuleList([
            copy.deepcopy(DeepSpeedTransformerLayer(config))
            for _ in range(config.num_hidden_layers)
        ])

    def forward(self, x, **kwargs):
        for layer in self.layers:
            x = layer(x, attention_mask=kwargs['attention_mask'])
        return x

    def get_attention_maps(self, x):
        attention_maps = []
        for layer in self.layers:
            _, attn_map = layer.self_attn(x, return_attention=True)
            attention_maps.append(attn_map)
            x = layer(x)
        return attention_maps


my_encoder = DeepSpeedTransformerEncoder(batch_size=1,
                                         hidden_size=20,
                                         heads=1,
                                         attn_dropout_ratio=0.0,
                                         hidden_dropout_ratio=0.0,
                                         num_hidden_layers=2,
                                         initializer_range=0.02,
                                         seed=42,
                                         fp16=True,
                                         pre_layer_norm=False,
                                         attn_dropout_checkpoint=False,
                                         normalize_invertible=False,
                                         gelu_checkpoint=False)

my_encoder = my_encoder.cuda()
x = torch.rand((1, 12896, 20)).cuda()
mask = torch.zeros(x.size()).cuda()
output = my_encoder(x, attention_mask=None)

criterion = nn.MSELoss()
loss = torch.sqrt(criterion(output, x))
loss.backward()

print(output)
print("output shape:", output.shape)
print("loss:", loss)

```
**Output**:
```
Traceback (most recent call last):
  File "src/deepspeed_test.py", line 63, in <module>
    output = my_encoder(x, attention_mask=None)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "src/deepspeed_test.py", line 31, in forward
    x = layer(x, attention_mask=kwargs['attention_mask'])
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 589, in forward
    return DeepSpeedTransformerFunction.apply(hidden_states,
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 205, in forward
    layer_norm_mean) = forward_func(config.layer_id,
TypeError: forward_fp16(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor, arg8: at::Tensor, arg9: at::Tensor, arg10: at::Tensor, arg11: at::Tensor, arg12: at::Tensor, arg13: at::Tensor, arg14: at::Tensor, arg15: bool, arg16: bool, arg17: bool, arg18: bool, arg19: bool) -> List[at::Tensor]
  ```
If I change the mask to all zeroes or all ones:
```python
zeros_mask = torch.zeros(x.size()).cuda()
output = my_encoder(x, attention_mask=zeros_mask)
print(output)
print("output shape:", output.shape)

loss = torch.sqrt(criterion(output, x))
loss.backward()
print("loss:", loss)
```
**I get this output**:
```
(autopath) [ftaj@mist001 autopath]$ python3 src/deepspeed_test.py
DeepSpeed Transformer config is  {'layer_id': 0, 'batch_size': 1, 'hidden_size': 20, 'intermediate_size': 80, 'heads': 1, 'attn_dropout_ratio': 0.0, 'hidden_dropout_ratio': 0.0, 'num_hidden_layers': 2, 'initializer_range': 0.02, 'fp16': True, 'pre_layer_norm': False, 'local_rank': -1, 'seed': 42, 'normalize_invertible': False, 'gelu_checkpoint': False, 'adjust_init_range': True, 'test_gemm': False, 'layer_norm_eps': 1e-12, 'training': True, 'is_grad_enabled': True, 'attn_dropout_checkpoint': False, 'stochastic_mode': False, 'return_tuple': False}
Using /scratch/l/lstein/ftaj/torch-extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /scratch/l/lstein/ftaj/torch-extensions/transformer/build.ninja...
Building extension module transformer...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer...
Time to load transformer op: 0.12398648262023926 seconds
layer #0 is created with date type [half].
DeepSpeed Transformer config is  {'layer_id': 1, 'batch_size': 1, 'hidden_size': 20, 'intermediate_size': 80, 'heads': 1, 'attn_dropout_ratio': 0.0, 'hidden_dropout_ratio': 0.0, 'num_hidden_layers': 2, 'initializer_range': 0.02, 'fp16': True, 'pre_layer_norm': False, 'local_rank': -1, 'seed': 42, 'normalize_invertible': False, 'gelu_checkpoint': False, 'adjust_init_range': True, 'test_gemm': False, 'layer_norm_eps': 1e-12, 'training': True, 'is_grad_enabled': True, 'attn_dropout_checkpoint': False, 'stochastic_mode': False, 'return_tuple': False}
layer #1 is created with date type [half].
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0',
       grad_fn=<DeepSpeedTransformerFunctionBackward>)
output shape: torch.Size([1, 12896, 20])
Traceback (most recent call last):
  File "src/deepspeed_test.py", line 84, in <module>
    loss.backward()
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 379, in backward
    grad_norm_b) = backward_func(
RuntimeError: Special sequence length found in softmax backward, seq_length: 12896
```

Note that only the backpropagation (`loss.backward()`) throws this error, and not the forward operation. It's also not clear to me why the model outputs nans.

Sometimes I've also gotten the following error, but I don't have a minimally reproducible example for it at the moment:
```
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 186, in forward
    input_mask = torch.cat((input_mask, torch.ones((inp_size[0], input_mask.shape[1], input_mask.shape[2], \
AttributeError: 'NoneType' object has no attribute 'shape'
```
It's as if the mask is not being properly passed to the transformer layers, particularly to `DeepSpeedTransformerFunction.apply` which needs the `attention_mask` to be passed to it:
https://github.com/microsoft/DeepSpeed/blob/8c56c25d84764dccf5979cb40a318bc3ccfac31a/deepspeed/ops/transformer/transformer.py#L589-L606

**Expected behavior**
I expected the transformer kernel to accept inputs of arbitrary lengths, at least up to 2^16.
If this is the wrong way of using the transformer kernel, then please provide tutorials on how to use it.

Thank you in advance!!!

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [YES] ...... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch']
torch version .................... 1.12.1
torch cuda version ............... 11.4
torch hip version ................ None
nvcc version ..................... 11.4
deepspeed install path ........... ['/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.7.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.4
```

**System info (please complete the following information):**
 - OS: Red Hat Enterprise Linux, 8.4
 - GPU count: 1x V100 with 32GB VRAM
 - Python version: 3.8.13

**Launcher context**
I'm using PyTorch Lightning, but the example above only relies on DeepSpeed and PyTorch.

**Comment by RezaYazdaniAminabadi** [comment] 2023-01-17 19:25
Hi @FarzanT,

Can you please try the mentioned PR and see if the issue is resolved?
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment] 2023-01-17 19:26
Btw, you need to convert the input to half-precision if you are running the model in fp16.

**Comment by tjruwase** [comment] 2023-01-27 19:14
Closed as fixed.

**Closed by tjruwase** 2023-01-27 19:14 UTC
Labels: bug, training

**Comment by FarzanT** [comment] 2023-01-31 17:27
@RezaYazdaniAminabadi So sorry about the delay. I tried the code again, but keep getting the `incompatible function arguments` error whether I use FP32 or FP16. Here's the error stack:
<details><summary>error stack</summary>

```
(autopath) [ftaj@mist010 autopath]$ python src/deepspeed_test.py
DeepSpeed Transformer config is  {'layer_id': 0, 'batch_size': 1, 'hidden_size': 20, 'intermediate_size': 80, 'heads': 1, 'attn_dropout_ratio': 0.0, 'hidden_dropout_ratio': 0.0, 'num_hidden_layers': 2, 'initializer_range': 0.02, 'fp16': False, 'pre_layer_norm': False, 'local_rank': -1, 'seed': 42, 'normalize_invertible': False, 'gelu_checkpoint': False, 'adjust_init_range': True, 'test_gemm': False, 'layer_norm_eps': 1e-12, 'training': True, 'is_grad_enabled': True, 'attn_dropout_checkpoint': False, 'stochastic_mode': False, 'return_tuple': False}
Using /scratch/l/lstein/ftaj/torch-extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /scratch/l/lstein/ftaj/torch-extensions/transformer/build.ninja...
Building extension module transformer...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer...
Time to load transformer op: 0.12723541259765625 seconds
layer #0 is created with date type [float].
DeepSpeed Transformer config is  {'layer_id': 1, 'batch_size': 1, 'hidden_size': 20, 'intermediate_size': 80, 'heads': 1, 'attn_dropout_ratio': 0.0, 'hidden_dropout_ratio': 0.0, 'num_hidden_layers': 2, 'initializer_range': 0.02, 'fp16': False, 'pre_layer_norm': False, 'local_rank': -1, 'seed': 42, 'normalize_invertible': False, 'gelu_checkpoint': False, 'adjust_init_range': True, 'test_gemm': False, 'layer_norm_eps': 1e-12, 'training': True, 'is_grad_enabled': True, 'attn_dropout_checkpoint': False, 'stochastic_mode': False, 'return_tuple': False}
layer #1 is created with date type [float].
Traceback (most recent call last):
  File "src/deepspeed_test.py", line 61, in <module>
    output = my_encoder(x, attention_mask=None)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "src/deepspeed_test.py", line 31, in forward
    x = layer(x)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 590, in forward
    return DeepSpeedTransformerFunction.apply(hidden_states,
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/ops/transformer/transformer.py", line 205, in forward
    layer_norm_mean) = forward_func(config.layer_id,
TypeError: forward_fp32(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor, arg8: at::Tensor, arg9: at::Tensor, arg10: at::Tensor, arg11: at::Tensor, arg12: at::Tensor, arg13: at::Tensor, arg14: at::Tensor, arg15: bool, arg16: bool, arg17: bool, arg18: bool, arg19: bool) -> List[at::Tensor]

Invoked with: 0, tensor([[[0.1487, 0.3856, 0.5506,  ..., 0.9704, 0.0138, 0.2983],
         [0.4680, 0.3104, 0.4892,  ..., 0.2222, 0.9438, 0.7927],
         [0.6202, 0.1822, 0.5068,  ..., 0.5873, 0.0115, 0.1649],
         ...,
         [0.3359, 0.4942, 0.7547,  ..., 0.4071, 0.2297, 0.5459],
         [0.7007, 0.3771, 0.4990,  ..., 0.9608, 0.4751, 0.1860],
         [0.8164, 0.1372, 0.7673,  ..., 0.7216, 0.3683, 0.0976]]],
       device='cuda:0'), None, Parameter containing:
tensor([[-3.3002e-03, -1.1765e-02, -4.2081e-02,  ...,  1.6111e-02,
          2.1495e-02, -3.8802e-06],
        [ 2.0040e-02,  2.8591e-03, -5.6750e-03,  ..., -5.0656e-03,
          2.4206e-03, -5.0356e-02],
        [ 3.4128e-02, -2.7348e-02,  3.9359e-02,  ...,  1.3303e-02,
         -1.3603e-02,  1.8982e-02],
        ...,
        [-4.8435e-02, -2.8943e-02,  1.8421e-02,  ..., -1.4936e-02,
          3.1662e-02, -6.5253e-02],
        [-3.4958e-02,  9.0777e-03, -9.6900e-03,  ...,  5.0486e-03,
         -1.8031e-02, -2.4532e-02],
        [-1.9560e-02,  1.2727e-02, -2.9703e-02,  ...,  2.8453e-02,
          2.5111e-02, -2.3717e-02]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0',
       requires_grad=True), Parameter containing:
tensor([[ 1.2744e-02,  8.2034e-03,  1.3912e-02, -1.5835e-02, -7.8946e-03,
          4.3736e-02, -1.6696e-02,  1.6892e-02,  8.6734e-03, -1.2889e-02,
         -1.1203e-02,  2.1723e-02, -1.2313e-02,  2.3240e-02,  2.9828e-03,
         -1.1231e-02,  3.6373e-03, -2.2909e-02, -2.0304e-02, -3.6692e-02],
        [-1.1350e-02, -7.8489e-03, -2.7064e-02, -2.3904e-02, -1.3229e-03,
         -1.6088e-02, -1.4689e-02, -1.5180e-02, -7.6868e-03, -1.3933e-02,
          1.4016e-02, -1.4042e-02,  1.2873e-02, -1.8898e-03, -1.9830e-02,
         -1.9452e-03, -3.9885e-02, -1.1890e-02,  2.5143e-02, -1.3798e-03],
        [ 9.8128e-03,  1.4955e-02, -2.2385e-02, -3.7531e-02,  2.0690e-02,
          9.5846e-03,  1.6624e-03,  3.8645e-02, -2.6902e-02, -1.6294e-02,
          3.4946e-02, -8.7995e-03, -2.2010e-03, -2.0935e-02, -2.2514e-03,
          1.0759e-02, -1.1799e-02, -1.5955e-02, -6.3633e-03, -7.7952e-03],
        [-9.3471e-03,  9.7403e-03, -4.1671e-04,  3.3993e-02, -1.4283e-02,
         -1.0933e-02, -1.0989e-02,  1.2230e-02,  1.4800e-02,  8.8439e-04,
         -4.0491e-03, -6.2340e-03,  3.6229e-02, -9.6122e-03,  4.4863e-02,
         -2.7278e-02, -4.8555e-03, -2.1075e-02,  3.5798e-02,  2.3134e-02],
        [ 3.8081e-02,  1.4616e-02,  9.4998e-03,  1.1421e-02, -1.3291e-02,
          2.0626e-02,  6.8058e-03,  2.4269e-02, -1.6999e-02, -2.5618e-03,
          2.4634e-02, -1.6154e-02,  2.6469e-02,  1.5702e-02,  3.0326e-02,
          1.7698e-02, -3.0697e-02, -1.0111e-02,  3.8534e-02,  5.8230e-05],
        [ 4.3827e-03, -1.7630e-02,  9.1881e-03,  2.6648e-02, -7.3743e-03,
         -1.1397e-02,  2.8143e-04, -6.2465e-03,  1.7357e-02,  6.3074e-03,
          1.0217e-02, -1.8160e-03, -2.0417e-02,  1.3366e-02,  6.5571e-03,
          2.2676e-02, -1.8568e-02,  1.4150e-02,  3.0253e-03,  1.8415e-02],
        [ 1.9022e-02,  2.5953e-02, -6.1044e-04,  8.6943e-03, -3.3803e-02,
         -1.8136e-02,  7.7165e-03, -2.5828e-02,  6.9537e-03,  3.5416e-02,
         -1.8422e-02, -3.0491e-02, -1.0097e-02,  8.3863e-04,  3.6094e-03,
         -4.3434e-03, -1.3211e-02,  2.7945e-02, -6.5688e-03,  1.1607e-02],
        [-1.5644e-02, -1.8125e-02, -1.2268e-02,  2.9060e-03,  1.4832e-02,
         -1.6492e-02, -9.0603e-04,  3.0345e-02, -7.6513e-03,  2.5811e-02,
          1.9475e-02,  1.3503e-02,  1.3871e-02,  4.1826e-04,  3.7112e-02,
         -3.0115e-03, -2.1040e-03, -4.9448e-05,  4.2562e-02,  3.5717e-02],
        [ 4.4195e-03, -1.1018e-03, -5.8581e-02, -1.0610e-02,  3.4149e-02,
          2.2500e-02, -1.4740e-02,  2.0393e-02, -1.6110e-02,  3.5804e-02,
          1.0273e-02,  2.2526e-02,  2.1278e-02,  4.7202e-02, -2.3376e-02,
         -3.9285e-03, -3.3291e-02,  1.7564e-02,  3.2718e-02, -1.2833e-02],
        [-5.5608e-03,  3.2442e-02, -1.3425e-02,  3.0487e-02,  9.1576e-03,
         -2.5049e-02,  2.2971e-02,  1.7024e-02, -1.9683e-02, -2.8912e-02,
          2.0866e-02, -3.5296e-02,  1.3663e-02,  7.3000e-03,  1.4383e-02,
         -2.0036e-02, -1.0225e-02, -1.1689e-02, -1.4282e-02, -8.6698e-03],
        [ 2.5304e-02,  1.4038e-02, -2.2166e-02, -3.0307e-02,  3.7365e-03,
         -1.2219e-02,  6.9058e-02,  9.9413e-04, -1.0532e-02,  1.2898e-02,
         -4.7078e-03, -4.4582e-03, -2.2589e-02, -4.7038e-04,  3.2781e-03,
         -9.0092e-03,  2.3515e-02,  1.0959e-02, -4.9423e-02, -5.8636e-03],
        [-4.3738e-02, -3.2644e-03,  7.4578e-05, -2.7683e-02,  3.7540e-03,
         -7.3961e-03, -1.9294e-02, -1.0827e-03, -2.4524e-03,  3.6777e-02,
         -2.3337e-02,  7.0274e-03,  3.1625e-02, -3.0791e-02,  6.4176e-03,
          1.5634e-02, -2.0605e-02, -9.1204e-03, -1.9651e-02,  1.6250e-02],
        [-1.6723e-02,  7.7015e-03, -2.3871e-03, -4.3707e-03,  1.5642e-02,
         -3.5689e-03,  2.0529e-02,  1.5691e-02, -3.7190e-02, -6.2119e-03,
          1.4255e-02, -2.5901e-02, -1.2010e-02, -3.8402e-03, -1.4558e-03,
          4.6680e-02, -3.8498e-03,  5.2188e-03, -1.5210e-02, -3.1021e-02],
        [ 6.6575e-03, -1.4354e-02,  1.2136e-03, -2.4361e-02, -4.9692e-03,
         -7.0575e-05,  2.9483e-02,  1.2246e-03, -2.9392e-02,  7.5376e-03,
         -3.8166e-03,  4.5346e-03, -9.8659e-03, -9.8966e-03, -1.7389e-02,
          2.9299e-02, -3.5603e-03, -4.7359e-02,  5.6058e-03,  2.2879e-02],
        [-1.6952e-02,  1.5972e-02, -9.1583e-03,  2.7999e-02, -1.4681e-02,
         -9.1271e-03, -4.0941e-02, -1.5279e-02, -4.8888e-02, -2.2214e-02,
          2.0943e-03, -6.2254e-03, -1.1365e-03, -1.3671e-03, -2.5154e-02,
          5.2072e-02, -2.6875e-02, -2.7829e-02,  1.6344e-02,  1.5796e-03],
        [-1.8801e-02, -1.8647e-02,  2.9195e-02, -3.5736e-03, -9.1714e-06,
         -1.2463e-03, -1.8528e-02,  6.5808e-03,  3.0730e-02,  1.9588e-02,
         -4.8347e-03, -1.0359e-02, -1.1795e-03, -2.7440e-02, -2.4040e-02,
          2.1684e-02, -1.6183e-02, -1.4925e-02,  1.7898e-02, -1.2397e-03],
        [ 3.9895e-02, -2.6713e-02, -2.2585e-02,  2.1271e-02, -8.5607e-03,
          5.2642e-03,  2.9845e-02,  9.2690e-03, -1.3688e-03, -3.8201e-02,
          6.4485e-03,  2.6103e-02, -2.5591e-02, -9.5227e-04,  2.4887e-02,
         -1.1253e-02, -5.3865e-03,  1.4616e-02,  2.6789e-02,  8.2356e-03],
        [ 6.7622e-03,  1.6775e-02,  2.1026e-03, -1.8144e-02, -2.7576e-02,
          6.6626e-03,  3.4697e-02,  1.3187e-02,  1.2279e-02,  9.0548e-03,
         -4.3621e-03,  2.7392e-02, -7.6565e-03,  2.4997e-02,  1.0964e-02,
          1.4553e-02, -5.7177e-03, -2.4526e-02, -1.0603e-02,  3.5062e-02],
        [-9.2760e-03,  3.9493e-03, -2.9035e-02,  6.7041e-03, -1.2717e-02,
         -2.9671e-03,  1.7285e-02,  7.1036e-03,  7.1180e-03,  9.0164e-04,
          1.3171e-02, -1.3848e-02,  6.5246e-04, -4.4872e-02,  2.3017e-02,
          2.5747e-02,  7.6164e-03,  4.8148e-03,  2.0062e-02, -1.2479e-02],
        [ 2.7942e-02,  1.5985e-02, -2.1342e-03,  2.1356e-02, -1.1386e-02,
         -1.3055e-02,  4.7147e-02,  1.4448e-02, -1.1682e-02, -3.7223e-03,
         -9.0454e-03,  1.2836e-02,  5.5116e-04,  6.5298e-04,  1.1433e-02,
          6.8436e-03,  1.2833e-02,  2.3571e-02,  6.4063e-03,  1.2320e-02]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0135,  0.0075, -0.0007,  ...,  0.0213, -0.0224, -0.0209],
        [ 0.0054, -0.0082, -0.0104,  ...,  0.0150,  0.0148, -0.0281],
        [-0.0080,  0.0071, -0.0113,  ...,  0.0019,  0.0099,  0.0297],
        ...,
        [ 0.0060, -0.0040, -0.0112,  ...,  0.0028, -0.0090, -0.0044],
        [-0.0118, -0.0080, -0.0018,  ...,  0.0092,  0.0077,  0.0215],
        [-0.0183,  0.0271, -0.0031,  ..., -0.0106, -0.0032,  0.0183]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-0.0326,  0.0440,  0.0143,  ..., -0.0183,  0.0282, -0.0131],
        [-0.0034, -0.0040, -0.0046,  ...,  0.0158,  0.0322,  0.0089],
        [-0.0157,  0.0025,  0.0152,  ..., -0.0085,  0.0094,  0.0055],
        ...,
        [ 0.0442, -0.0002,  0.0110,  ...,  0.0094,  0.0007, -0.0080],
        [-0.0270, -0.0029,  0.0120,  ...,  0.0216, -0.0183, -0.0358],
        [-0.0161, -0.0149,  0.0027,  ..., -0.0020,  0.0039,  0.0196]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0', requires_grad=True), True, False, False, False, False
```

</details>

I'm not sure if it's just a type error. Most arguments to `forward_fp32()` and `forward_fp16()` are supposed to be `Tensor`, but somehow they are getting passed `Parameter` containing a `Tensor`. Perhaps this is what's causing the error?
Should a separate issue be opened for this?

Thank you for your time and sorry again for the delay.
