### ISSUE TITLE
Importing DeepSpeed causes a ResourceWarning on closing Python [BUG]

### ISSUE THREAD

**Issue by rosario-purple** [microsoft/DeepSpeed#4793] opened 2023-12-09 19:46 UTC
**Describe the bug**
When I do "import deepspeed" in Python, then close out Python, I see a "ResourceWarning" error message:

```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepspeed
[2023-12-09 11:39:38,619] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
>>> 
/scratch/miniconda3/envs/brr/lib/python3.10/tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpr4xh3nmn'>
  _warnings.warn(warn_message, ResourceWarning)
```

(The error only happens when I close Python, not at import time.)

**To Reproduce**
Install DeepSpeed 0.12.4 over Pip, run Python, do "import deepspeed", then close the Python application.

**Expected behavior**
Importing should run without warnings.

**ds_report output**
```
[2023-12-09 11:44:15,590] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/scratch/miniconda3/envs/brr/lib/python3.10/site-packages/torch']
torch version .................... 2.1.1+cu121
deepspeed install path ........... ['/scratch/miniconda3/envs/brr/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.12.4, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 472.43 GB
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU count and types: 8x A100 80 GB
 - Interconnects (if applicable): N/A
 - Python version: 3.10.13
 - Any other relevant info about your setup

**Launcher context**
Doing "import deepspeed" from Python.

**Docker context**
N/A

**Additional context**
N/A

**Comment by loadams** [comment] 2023-12-11 18:21
Hi @rosario-purple - I'm not able to reproduce this on my side:

```
> pip list
deepspeed                     0.12.4+a3926bbb
```

``` 
> python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepspeed
[2023-12-11 18:14:00,556] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
>>>
```

It looks like the error may be coming from here: `/scratch/miniconda3/envs/brr/lib/python3.10/tempfile.py` and based on other answers online I'm seeing this can come from pytorch or other sources as well.  So I don't believe this is a DeepSpeed bug, since the warning is letting us know that python cleaned up that temp directory for us.  

Are you able to do any additional debug to see if this is coming from DeepSpeed?

**Comment by loadams** [comment] 2023-12-14 21:50
Hi @rosario-purple - I'm going to close this since I cannot find a way to repro it.  If you're able to, or are able to trace this to DeepSpeed, please let me know, but closing this for now, thanks!

**Closed by loadams** 2023-12-14 21:50 UTC
Labels: bug, training
