### ISSUE TITLE
Deepspeed's FlopsProfiler didn't work in my project

### ISSUE THREAD

**Issue by Firefly-Dance** [microsoft/DeepSpeed#4075] opened 2023-08-01 08:42 UTC
I want to extend FlopsProfiler to my project, but I have trouble in using it in my project.

Basically, I copy code in get_model_profile, but it didn't work as expected.

Modified code as below.

    if warm_up is not None:
        from deepspeed.flops_profiler.profiler import FlopsProfiler
        assert isinstance(model, nn.Module), "model must be a PyTorch module"
        prof = FlopsProfiler(model)
        model.eval()
    try:
        input = torch.ones(()).new_empty(
            (*input_size, ),
            dtype=next(model.parameters()).dtype,
            device=next(model.parameters()).device,
        )
    except StopIteration:
        input = torch.ones(()).new_empty((*input_size, ))

    args = [input]

    assert (len(args) > 0) or (len(kwargs) > 0), "args and/or kwargs must be specified if input_shape is None"
    for _ in range(warm_up):
        print("Warm up epochs:",_)
        if kwargs:
            if mode == 'forward':
                _ = model(*args, **kwargs)
            if mode == 'generate':
                _ = model.generate(*args, **kwargs)
        else:
            if mode == 'forward':
                _ = model(*args)
            if mode == 'generate':
                _ = model.generate(*args)
                
    prof.start_profile(ignore_list=ignore_modules)
    
    if kwargs:
        if mode == 'forward':
            _ = model(*args, **kwargs)
        if mode == 'generate':
            _ = model.generate(*args, **kwargs)
    else:
        if mode == 'forward':
            _ = model(*args)
        if mode == 'generate':
            _ = model.generate(*args)

    prof.print_model_profile(profile_step=warm_up,
                                module_depth=-1,
                                top_modules=1,
                                detailed=True,
                                output_file=None)
    
    prof.end_profile()

And the result is :
![image](https://github.com/microsoft/DeepSpeed/assets/63177590/b110dd66-c340-4f6e-b5f0-fd659acdb294)

Which means FlopsProfiler didn't really get **MACs** and **flops** while model running, they remain in 0 as origin.

I didn't get the reason for this, since _prof.start_profile_ seems works, but the result is not that well as expected.

I have tried using get_model_profile, and it works. 

    from deepspeed.flops_profiler.profiler import get_model_profile
    get_model_profile(
                        model=model, # model
                        input_shape=input_size, # input shape to the model. If specified, the model takes a tensor with this shape as the only positional argument.
                        args=None, # list of positional arguments to the model.
                        kwargs=None, # dictionary of keyword arguments to the model.
                        print_profile=True, # prints the model graph with the measured profile attached to each module
                        detailed=True, # print the detailed profile
                        module_depth=-1, # depth into the nested modules, with -1 being the inner most modules
                        top_modules=1, # the number of top modules to print aggregated profile
                        warm_up=10, # the number of warm-ups before measuring the time of each module
                        as_string=True, # print raw numbers (e.g. 1000) or as human-readable strings (e.g. 1k)
                        output_file=None, # path to the output file. If None, the profiler prints to stdout.
                        ignore_modules=None,# the list of modules to ignore in the profiling
                        # mode == 'forward' # change to 'generate' if use model.generate(*args)
                    ) 

**System info:**
- Jetson AGX orin (seems not matter so much)
- CPU aarch64
- GPU orin
- pytorch 1.12.0a0+2c916ef.nv22.3
- python 3.8.13

**Comment by ShijieZZZZ** [comment] 2023-09-22 23:13
Hello, it looks like all the four **if mode==** statements are false. Could you make sure that "mode" can be only "forward" or "generate" here?
```
if kwargs:
    if mode == 'forward':
        _ = model(*args, **kwargs)
    if mode == 'generate':
        _ = model.generate(*args, **kwargs)
else:
    if mode == 'forward':
        _ = model(*args)
    if mode == 'generate':
        _ = model.generate(*args)
```

**Comment by Firefly-Dance** [comment] 2023-09-23 01:31
> Hello, it looks like all the four **if mode==xxx** statements are false. Could you make sure that "mode" can be only "forward" or "generate" here?
> 
> ```
> if kwargs:
>     if mode == 'forward':
>         _ = model(*args, **kwargs)
>     if mode == 'generate':
>         _ = model.generate(*args, **kwargs)
> else:
>     if mode == 'forward':
>         _ = model(*args)
>     if mode == 'generate':
>         _ = model.generate(*args)
> ```
I'm pretty sure about this.
Only this two methods are allowed, **forward** are used in CV-like tasks and **generate** are used in LLM tasks.

**Comment by ShijieZZZZ** [comment] 2023-09-25 18:58
I did not see where `mode` value is set. Are you sure that `model()` or `model.generate()` is executed?

Also do you have a small example to reproduce the issue?

**Comment by ShijieZZZZ** [comment] 2023-10-09 18:43
Hi, I will close this issue for now. 
Feel free to reopen when there is an update.

**Closed by ShijieZZZZ** 2023-10-09 18:43 UTC
