### ISSUE TITLE
FusedAdam Hangs during Initialization

### ISSUE THREAD

**Issue by lipiji** [microsoft/DeepSpeed#3430] opened 2023-05-03 04:35 UTC
I am testing the accelerate training code and I modify the optimizer of: https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py#L141 
to the FusedAdam (from deepspeed.ops.adam import FusedAdam), then after "python ./nlp_example.py" I find that the progress hands on the line of "optimizer = FusedAdam(params=model.parameters(), lr=lr)".

What are the possible reasons?
https://github.com/huggingface/accelerate/tree/main/examples

**Comment by jomayeri** [comment] 2023-05-04 19:27
Hi @lipiji I was unable to reproduce the bug. Could you provide information about the environment setup you are using?

**Comment by jomayeri** [comment] 2023-05-11 22:25
Closing now. Feel free to reopen if needed.

**Closed by jomayeri** 2023-05-11 22:25 UTC
Labels: bug, training
