### ISSUE TITLE
Flops Profiler breaks after running

### ISSUE THREAD

**Issue by sdtblck** [microsoft/DeepSpeed#739] opened 2021-02-09 15:57 UTC
I am able to profile my model by adding the following to my config:

```json
  "flops_profiler": {
    "enabled": true,
    "start_step": 5,
    "end_step": 10,
    "module_depth": -1,
    "top_modules": 3
  }
```

It returns the profile result, however it seems to break straight after. 
Traceback:
```
  File "pretrain_gpt2.py", line 156, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/root/megatron-3d/megatron/training.py", line 97, in pretrain
    iteration = train(forward_step_func,
  File "/root/megatron-3d/megatron/training.py", line 481, in train
    loss_dict, skipped_iter = train_step(forward_step_func,
  File "/root/megatron-3d/megatron/training.py", line 324, in train_step
    return train_step_pipe(model, data_iterator)
  File "/root/megatron-3d/megatron/training.py", line 358, in train_step_pipe
    loss = model.train_batch(data_iter=data_iterator)
  File "/root/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 283, in train_batch
    self._exec_schedule(sched)
  File "/root/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 1172, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 521, in _exec_forward_pass
    outputs = super().forward(inputs)
  File "/root/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 824, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 719, in _call_impl
    result = hook(self, input)
  File "/root/anaconda3/lib/python3.8/site-packages/deepspeed/profiling/flops_profiler/profiler.py", line 49, in pre_hook
    module.__steps__ += 1
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'GPT2ModelPipe' object has no attribute '__steps__'
```

**Comment by cli99** [comment] 2021-02-09 20:09
Can you please try out this PR https://github.com/microsoft/DeepSpeed/pull/682 to see if the issue is fixed? If not. Could you please share your deepspeed config file?

**Comment by redhairdragon** [comment] 2021-02-10 01:04
I had the same issue. And the PR works for me

> Can you please try out this PR #682 to see if the issue is fixed? If not. Could you please share your deepspeed config file?

**Comment by cli99** [comment] 2021-02-11 02:07
Thanks for trying the PR. Profile across multiple steps is now changed to a single step. It's now merged into the master.

**Closed by cli99** 2021-02-11 02:07 UTC
