### ISSUE TITLE
[BUG] No runnable example for MoE / PR-MoE GPT inference

### ISSUE THREAD

**Issue by YJHMITWEB** [microsoft/DeepSpeed#4039] opened 2023-07-25 21:52 UTC
Hi, currently with several releases on the `DeepSpeed` branch and the `Megatron-DeepSpeed` branch, I find it very hard to run those examples provided in the repo due to compatibility issues. And I am also not sure at this moment, what are the compatible branches of `DeepSpeed` and `Megatron-DeepSpeed` that come with runnable examples of MoE GPT train/inference. 

For example, currently under `Megatron-DeepSpeed/examples_deepspeed/MoE`, those `MoE` training scripts actually do not use MoE at all, instead, they just leave the `num_experts=1` unchanged. 

Also, I am also wondering if there will be any runnable example of the PR-MoE GPT as described in the paper [https://arxiv.org/abs/2201.05596](url).

**Comment by conglongli** [comment] 2023-07-25 22:08
@YJHMITWEB First of all, as I explained in other issues your created&closed, what you claimed is not true. Under https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples_deepspeed/MoE, any script with "MoE" in their file names are MoE examples, any script with "PR-MoE" in their file names are PR-MoE examples, any script with "dense" in their file names are non-MoE dense model examples for comparison.

Second, about the separate "No runnable example for MoE / PR-MoE GPT inference" issue mentioned in issue title, I believe your are talking about the issue https://github.com/microsoft/Megatron-DeepSpeed/issues/179 you created before, but in both these two issues you didn't provide any information about what error you hit (after adding back the p2p_communication.py) and how to reproduce it. We need those information in order to debug this.

**Comment by YJHMITWEB** [comment] 2023-07-25 23:58
Hi @conglongli , thanks for the clarification. 

In current `Megatron-DeepSpeed` branch, I took some experiments with `ds_pretrain_125M_MoE64.sh` without modifying any settings. And I simply hack into `/Megatron-DeepSpeed/megatron/model/transformer.py` by adding one line `print(self.num_experts)` at:
```
        # MLP
        self.num_experts = num_experts
        print(self.num_experts)
        if args.num_experts_switch is not None:
            self.mlp = SwitchMLP(config) # Megatron-LM's MoE
        else:
            if self.num_experts <= 1: # dense, not MoE
                self.mlp = ParallelMLP(config)
            else: # DeepSpeed's MoE
                enable_expert_tensor_parallelism = args.enable_expert_tensor_parallelism
                self.mlp = MoE(args.hidden_size,
                                ParallelMLP(config,
                                    moe=True,
                                    enable_expert_tensor_parallelism=enable_expert_tensor_parallelism),
                                num_experts=self.num_experts,
                                ep_size=args.moe_expert_parallel_size,
                                k=args.topk,
                                use_residual=(args.mlp_type == 'residual'),
                                capacity_factor=args.moe_train_capacity_factor,
                                eval_capacity_factor=args.moe_eval_capacity_factor,
                                min_capacity=args.moe_min_capacity,
                                drop_tokens=args.moe_token_dropping, use_tutel=args.use_tutel,
                                enable_expert_tensor_parallelism=enable_expert_tensor_parallelism)
```
And I found out the `num_experts` it actually running with is always `1` as the related parameters are never passed into it.

**Comment by conglongli** [comment] 2023-07-26 00:35
Did you print all layers' num_experts? Because we only convert every other layer to MoE so there will be half of layers with num_experts = 1 regardless of what you config is set https://github.com/microsoft/Megatron-DeepSpeed/blob/main/megatron/model/transformer.py#L1620-L1627

**Comment by YJHMITWEB** [comment] 2023-07-26 00:57
Yes, I did print all the layers and I do believe that no MoE layers have been really initiated as the `num_experts` is not passed into the model initialization.

**Comment by conglongli** [comment] 2023-07-26 20:52
I need to do some investigation but currently I'm busy with other urgent tasks. Will hopefully get back to you early next week.

**Comment by conglongli** [comment] 2023-08-01 08:36
@YJHMITWEB I just merged a PR https://github.com/microsoft/Megatron-DeepSpeed/pull/192 which fixes this issue (plus other issues related to DeepSpeed MoE training).

**Closed by conglongli** 2023-08-01 08:36 UTC
Labels: bug, inference

**Comment by YJHMITWEB** [comment] 2023-08-02 21:50
Thanks for the effort! @conglongli
