### ISSUE TITLE
nvcc fatal unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by szhengac** [microsoft/DeepSpeed#607] opened 2020-12-16 05:57 UTC
When I install deepspeed from source, it gives me `nvcc fatal unsupported gpu architecture 'compute_86'`. My cuda version is 11.0. I can alleviate the issue by skipping 'compute_86' in https://github.com/microsoft/DeepSpeed/blob/6380ee35116dfc7c2a037d48fbd790d8dbabfc1d/op_builder/builder.py#L265. I think the current deepspeed installation may not handle cuda 11.0 well.

**Comment by sxjscience** [comment] 2021-01-07 01:20
I'm also having this issue. The root cause should be that compute_86 is not supported in CUDA 11.0 and will only be available in CUDA>=11.1. Thus, we should be able to solve it by revising the logic to include the special treatment of CUDA 11.0 https://github.com/microsoft/DeepSpeed/blob/44bd538b110ce0e8fc69626854631c3aee0dc094/op_builder/builder.py#L37-L39

**Comment by YaoBeiji** [comment] 2021-01-26 07:25
nvcc fatal   : Unsupported gpu architecture 'compute_86'，I have this issue too，but my  CUDA version is 10.2

**Comment by loadams** [comment] 2023-08-18 21:27
Closing this issue since this was a case where the CUDA version had to be updated to get support for newer devices, as is often the case.

**Closed by loadams** 2023-08-18 21:27 UTC
