### ISSUE TITLE
Fail to install sparse attention and cpu-adam

### ISSUE THREAD

**Issue by szhengac** [microsoft/DeepSpeed#459] opened 2020-10-03 00:05 UTC
When I used install.sh, I received the following warnings:

`[WARNING]  fused lamb is NOT installed.

 [WARNING]  transformer kernels are NOT installed.

 [WARNING]  sparse attention is NOT installed.

 [WARNING]  cpu-adam (used by ZeRO-offload) is NOT installed.`

After changing the wheel installation to pure pip installation, the fused lamb and transformer kernel can be installed. But I still fail to install the sparse attention and cpu-adam.

**Comment by ollmer** [comment] 2020-10-06 16:37
Hi! I have the same issue after installing with install.sh in virtual environment

**Comment by tjruwase** [comment] 2020-10-06 17:23
@ollmer Can you please share the exact command you ran?

**Comment by ollmer** [comment] 2020-10-06 17:48
`./install.sh`
Tail of the output:


 Installing collected packages: deepspeed
Successfully installed deepspeed-0.3.0+6717638
Removed build tracker: '/tmp/pip-req-tracker-kxo93qrf'
 [SUCCESS]  deepspeed successfully imported.
 [INFO] torch install path: ['/home/olg/venv/lib/python3.6/site-packages/torch']
 [INFO] torch version: 1.5.0+cu101, torch.cuda: 10.1
 [INFO] deepspeed install path: ['/home/olg/venv/lib/python3.6/site-packages/deepspeed']
 [INFO] deepspeed info: 0.3.0+6717638, 6717638, master
 [SUCCESS]  apex extensions successfully installed
 [INFO] using new-style apex
 [SUCCESS]  fused lamb successfully installed.
 [SUCCESS]  transformer kernels successfully installed.
 [WARNING]  sparse attention is NOT installed.
 [WARNING]  cpu-adam (used by ZeRO-offload) is NOT installed.
Installation is successful
`

**Comment by tjruwase** [comment] 2020-10-06 18:02
Thanks for sharing.  Now it seems installation is successful, although cpu-adam and sparse-attention are not installed. Those two are not installed by default because of dependencies. So two questions:
1) Does this mean the installation error is not reproducible?
2) Can you test if the installation works for you?

**Comment by ollmer** [comment] 2020-10-06 18:07
It's more like what should i do to get sparse attention module and cpu-adam installed? Because i want to do some experiments with both of them. My expectation was that all of deepspeed optimizations would be available after install by default.

**Comment by tjruwase** [comment] 2020-10-06 18:24
Got it. Unfortunately, sparse-attention and cpu-adam have extra requirements that could create installation issues and so they are disabled by default to reduce the number of users who run into these issues. 

To enable cpu-adam please 
1. Install cpufeature: `pip install cpufeature`

2. Run `DS_CPU_ADAM=1 ./install.sh -n`
The `-n` is for incremental installation so that it does not rebuild existing binaries. 

My colleague will respond with installation details for sparse-attention.

**Comment by ollmer** [comment] 2020-10-06 18:49
Thanks for instructions!

> pip install cpufeature

This one already has been installed.

> DS_CPU_ADAM=1 ./install.sh -n

I've done it, it takes less than a minute, but the result is the same, unfortunately:

Installing collected packages: deepspeed
Successfully installed deepspeed-0.3.0+6717638
Removed build tracker: '/tmp/pip-req-tracker-5vxjp6gi'
 [SUCCESS]  deepspeed successfully imported.
 [INFO] torch install path: ['/home/jovyan/venv/lib/python3.6/site-packages/torch']
 [INFO] torch version: 1.5.0+cu101, torch.cuda: 10.1
 [INFO] deepspeed install path: ['/home/jovyan/venv/lib/python3.6/site-packages/deepspeed']
 [INFO] deepspeed info: 0.3.0+6717638, 6717638, master
 [SUCCESS]  apex extensions successfully installed
 [INFO] using new-style apex
 [SUCCESS]  fused lamb successfully installed.
 [SUCCESS]  transformer kernels successfully installed.
 [WARNING]  sparse attention is NOT installed.
 [WARNING]  cpu-adam (used by ZeRO-offload) is NOT installed.
Installation is successful

**Comment by arashashari** [comment] 2020-10-06 18:55
And for installing Sparse Attention, you have the following dependencies:
- llvm:       sudo apt-get install llvm-9-dev
- cmake:   sudo apt-get install cmake 
- triton>=0.2.2:  this will be handled by the installer script, if there was any issue, please install it through pip

Then you need to set the install flag:
DS_BUILD_SPARSE_ATTN=1 (for sparse attention)
DS_BUILD_CPU_ADAM=1 (for cpu adam)

and finally run ./install.sh

Please update us on the result.

**Comment by tjruwase** [comment] 2020-10-06 19:10
@arashashari  Thanks for fixing my typo on DS_BUILD_CPU_ADAM

**Comment by arashashari** [comment] 2020-10-06 19:32
@ollmer: great. We will keep the issue open. Please keep us updated and we will close it when you were able to successfully install SA as well.

**Comment by szhengac** [comment] 2020-10-06 22:59
I failed to import triton after pip install it. So I have to compile it from source with several other dependencies. After these, I can install sparse attention successfully.

**Comment by ollmer** [comment] 2020-10-08 09:31
@arashashari: i have to wait for a few days for the llvm availability on our platform. I will let you know when i'll try again, thanks!

**Comment by ollmer** [comment] 2020-10-16 15:50
@arashashari: I've managed to get llvm and everything installs and works smoothly now. Thanks for help!

**Comment by arashashari** [comment] 2020-10-16 16:11
@ollmer: fantastic, happy to hear it. I close the issue now.

**Closed by arashashari** 2020-10-16 16:11 UTC

**Comment by VardanyanS** [comment] 2021-02-17 22:36
> I've managed to get llvm and everything installs and works smoothly now

Hi, I have the same problem, could you please explain, how you got llvm?

**Comment by ollmer** [comment] 2021-02-18 15:40
My cloud provider just build the base image with it for me.
