### ISSUE TITLE
How deepspeed loads checkpoint?

### ISSUE THREAD

**Issue by szhengac** [microsoft/DeepSpeed#465] opened 2020-10-08 06:14 UTC
Hi, by looking at the engine code, it seems to me that only the first DP process saves the model file. Then how other DP processes on different nodes load the checkpoint? I cannot find the lines of code for broadcasting model parameters from the DP rank 0 to other DP processes after calling `load_checkpoint` in DeepSpeedExample Bing-BERT or Megatron GPT-2.

Also, as DP processes on other nodes receive a [None type of load_path](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1201), they will skip the `_load_zero_checkpoint`. For the processes on the same node as the first DP process, they cannot see the `zero_ckpt` on other nodes and will [skip the loading zero checkpoints as well](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1316-L1320). I received these warnings when I used Megatron BERT with deepspeed and observed hanging job.

**Comment by tjruwase** [comment] 2020-10-08 20:04
@szhengac Thanks for using DeepSpeed.  Yes, in the engine code, only the first DP process saves the model file, but this is not a problem as I will explain below. 

The DeepSpeed approach to checkpointing is that all clients call save_checkpoint() and load_checkpoint(). For the save_checkpoint(), the engine allows only first the DP process to write a model file. Note that this is simply an optimization since model states on all the DP processes are the same. For load_checkpoint(), the engine allows all the DP processes to read the model file. For example for BingBert, you can see that [load_checkpoint()](https://github.com/microsoft/DeepSpeedExamples/blob/ba63ad0fa861d28b3b33bc2c20f702647403e258/bing_bert/deepspeed_train.py#L62) and [save_checkpoint()](https://github.com/microsoft/DeepSpeedExamples/blob/ba63ad0fa861d28b3b33bc2c20f702647403e258/bing_bert/deepspeed_train.py#L47) are called by all DP processes. 

Are you seeing any problems relating to this with BingBert or Megatron GPT-2? It is possible that Megatron BERT has problems because we have not ported that model to use DeepSpeed.

**Comment by szhengac** [comment] 2020-10-08 20:55
@tjruwase Thanks for your response. I do see the issue when I add deepspeed to Megatron BERT. 

Since the model state is only stored by the first DP process, the processes on other nodes cannot see the model state, and they skip the loading. So this means this [warning](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1219) is called.

In my example, I use 2 nodes with 8 gpus per node. When the workers on the root node tries to load the zero checkpoint, I get the warning like: `f"Client provided zero checkpoint load paths: ['zero_pp_rank_08_5000_mp_rank_00optim_states.pt', 'zero_pp_rank_09_5000_mp_rank_00optim_states.pt', 'zero_pp_rank_10_5000_mp_rank_00optim_states.pt', ..., 'zero_pp_rank_15_5000_mp_rank_00optim_states.pt'] does not exist"`

I check the saving & loading part of Megatron GPT-2 and BERT, but I do not see much difference. Two scripts have very similar code structure.

**Comment by tjruwase** [comment] 2020-10-08 21:09
So I see that checkpoint files are not the model state checkpoints, but rather the ZeRO optimizer state checkpoints. Unlike, the model state checkpoint, each DP process generates a ZeRO optimizer state checkpoint. So the warning is indicating that all the ZeRO checkpoints are not being created, which is unexpected. So can we debug step-by-step as follows:

1) Can you run Megatron BERT without ZeRO? 

2) Can you share/examine the log with ZeRO enabled to find this [message ](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1416)indicating whether ZeRO checkpoints are created?

**Comment by tjruwase** [comment] 2020-10-08 21:13
Also, the load paths like `zero_pp_rank_08_5000_mp_rank_00optim_states.pt` suggests to me that the checkpoints are being generated on local disk which could make them inaccessible to the processes on the root node. Can you try writing the checkpoints to a shared directory that is accessible to both nodes?

**Comment by szhengac** [comment] 2020-10-08 22:13
I can see that both mode state and zero (optimizer) checkpoints are created
under my specified folder. For node 1 , it has model state file and 8 zero
checkpoints for 8 gpus, and the 2nd node only has 8 zero checkpoints for
its 8 gpus. That’s why I mentionEd that the 2nd node can not access to the
model state saved by the first node.

 I will try a shared file system. Based on the code, I think this should
work. But for our usage, we may not go with the shared file system.

**Comment by tjruwase** [comment] 2020-10-08 22:20
What you have described so far is expected behavior, i.e., node 1 has 1 model checkpoint file and 8 zero checkpoints files, while node 2 has 8 zero checkpoint files. Please share your experience with the shared file system.

**Comment by szhengac** [comment] 2020-10-08 22:25
But then how the 2nd node loads the model parameters as it does not have access to the local disk on the first node? I think the model parameters are stored in the model state checkpoint?

**Comment by tjruwase** [comment] 2020-10-08 22:30
Yes, this is a mystery to me as well. Can you please share your log or at least the parts showing either this [message](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1223) or this [one](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/engine.py#L1218)?

**Comment by tjruwase** [comment] 2020-10-08 22:32
Also, for the sake of narrowing down the issue, can you test a single node run to see if that works? That could help to confirm that this is a multi-node problem.

**Comment by szhengac** [comment] 2020-10-08 22:34
I just found this [line of code](https://github.com/microsoft/DeepSpeed/blob/c39a76fed71f87fd0b026cf6dfd1aee8283319ed/deepspeed/runtime/pipe/module.py#L567) is called in _load_checkpoint. This calls broadcast. 

It will take some time for me to go with 2-nodes again as my account does not have enough capacity at the moment.

I can test a single node first again.

**Comment by szhengac** [comment] 2020-10-08 22:51
For a single node training, I can see that all the model state and checkpoints are loaded properly.

[2020-10-08 22:46:38,922] [INFO] [engine.py:1220:_load_checkpoint] rank: 1 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:38,989] [INFO] [engine.py:1220:_load_checkpoint] rank: 6 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,071] [INFO] [engine.py:1220:_load_checkpoint] rank: 4 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,111] [INFO] [engine.py:1220:_load_checkpoint] rank: 3 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,144] [INFO] [engine.py:1220:_load_checkpoint] rank: 7 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,201] [INFO] [engine.py:1220:_load_checkpoint] rank: 2 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,238] [INFO] [engine.py:1220:_load_checkpoint] rank: 0 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
[2020-10-08 22:46:39,281] [INFO] [engine.py:1220:_load_checkpoint] rank: 5 loading checkpoint: checkpoints/bert_345m/500/mp_rank_00_model_states.pt
successfully loaded 8 ZeRO state_dicts for rank 1
successfully loaded 8 ZeRO state_dicts for rank 2
successfully loaded 8 ZeRO state_dicts for rank 0
successfully loaded 8 ZeRO state_dicts for rank 3
successfully loaded 8 ZeRO state_dicts for rank 6
successfully loaded 8 ZeRO state_dicts for rank 4
successfully loaded 8 ZeRO state_dicts for rank 7
successfully loaded 8 ZeRO state_dicts for rank 5
loading 8 zero partition checkpoints for rank 1
loading 8 zero partition checkpoints for rank 0
loading 8 zero partition checkpoints for rank 2
loading 8 zero partition checkpoints for rank 5
loading 8 zero partition checkpoints for rank 4
loading 8 zero partition checkpoints for rank 6
loading 8 zero partition checkpoints for rank 7
loading 8 zero partition checkpoints for rank 3
  successfully loaded checkpoints/bert_345m/500/mp_rank_00_model_states.pt

**Comment by szhengac** [comment] 2020-10-24 01:43
@tjruwase I can confirm that the loading works with shared file system. Without the shared file system, I will receive the errors I mentioned above.

**Comment by tjruwase** [comment] 2020-10-24 04:12
@szhengac Thanks for the update. Closing now.

**Closed by tjruwase** 2020-10-24 04:12 UTC

**Comment by szhengac** [comment] 2020-10-27 00:30
@tjruwase Is there any plan to make it work for multi-node without shared file system.

**Comment by gordicaleksa** [comment] 2023-11-28 21:25
same question as @szhengac - any plans to support the situation where each node has its own output storage?

I basically have 2 servers on the same intranet but no shared storage, i figured out I have to manually copy files around to get it to work
