### ISSUE TITLE
zero_to_fp32.py still imports a wrong model after fix

### ISSUE THREAD

**Issue by xycforgithub** [microsoft/DeepSpeed#1317] opened 2021-08-19 22:34 UTC
Same as #1165; the issue is closed now so I'm opening a new one. 
It looks like the zero_to_fp32.py still cannot load the correct weights under multi-gpu and ZERO-2 setting.

Loading 'mp_rank_00_model_states.pt':

states['module']['deberta.encoder.layer.0.output.dense.weight']
tensor([[-0.0211, 0.0068, 0.0206, ..., 0.0057, 0.0316, 0.0256],
[ 0.0273, 0.0141, 0.0118, ..., -0.0122, 0.0054, 0.0010],
[ 0.0479, -0.0237, -0.0604, ..., -0.0340, -0.0183, 0.0691],
...,
[ 0.0270, -0.0231, 0.0218, ..., 0.0563, 0.0641, -0.0094],
[-0.0563, -0.0837, -0.0427, ..., 0.0242, -0.0132, -0.0512],
[-0.0012, 0.0064, 0.0465, ..., 0.0219, 0.0259, -0.0281]],
device='cuda:0', dtype=torch.float16)

Loading the exported weights using `load_state_dict_from_zero_checkpoint`:
(Pdb) self.deberta.encoder.layer[0].output.dense.weight
Parameter containing:
tensor([[ 0.0207, -0.0448, 0.0022, ..., 0.0406, -0.0338, -0.0174],
[-0.0577, -0.0648, 0.0404, ..., 0.0108, -0.0167, -0.0100],
[ 0.0548, 0.0063, 0.0024, ..., 0.0311, 0.0249, 0.0167],
...,
[-0.0081, 0.0194, -0.0266, ..., -0.0269, -0.0002, 0.0257],
[ 0.0202, -0.0002, 0.0831, ..., -0.0008, -0.0094, 0.0258],
[-0.0320, 0.0529, -0.0259, ..., 0.0117, -0.0292, -0.0064]],

I'm using Deepspeed 0.4.5. I can confirm the problem happens on 2gpus, and not on 1gpu.

**Comment by stas00** [comment] 2021-08-20 16:05
@tjruwase, any chance you guys can take over the maintenance of zero_to_fp32, as I can't keep up with the changes in the core. It's the best that any changes you do get synced with the weights re-consolidation code in tandem.

I created the initial tests here:
https://github.com/microsoft/DeepSpeed/blob/10b48405ab0e69a1caf455f445526c4b39b0dbb8/tests/unit/test_zero.py#L135

So it's probably extending those to include the new variations that Deepspeed is extended to support.

As I suggested ealier perhaps the reconstruction code should be moved along side the partitioning code for each stage, so that they are in the same file and thus are easier to maintain in sync.

So here is how the model gets partitioned, and here is how it gets unpartitioned, one next to each other.

**Comment by tjruwase** [comment] 2021-08-23 21:40
@jeffra, FYI

**Comment by tjruwase** [comment] 2021-09-12 01:35
@xycforgithub, apologies for the delayed response. Can you please check if this is still an issue as some checkpointing related fixes were recent pushed? If it is still an issue can you please share more details to help repro? Thanks for your patience.

**Comment by xycforgithub** [comment] 2021-09-15 04:47
@tjruwase , I can verify the problem is still there in Deepspeed 0.5.2. I saved a model checkpoint in the middle of training. I then used ``load_state_dict_from_zero_checkpoint(model, ds_dir, tag=str(self.config.start_model_step))`` to load the checkpoint (it is a DeBERTa model), and I get
(Pdb) model.deberta.encoder.layer[0].output.dense.weight
Parameter containing:
tensor([[ 0.0207, -0.0448,  0.0022,  ...,  0.0406, -0.0338, -0.0174],
        [-0.0577, -0.0648,  0.0404,  ...,  0.0108, -0.0167, -0.0100],
        [ 0.0548,  0.0063,  0.0024,  ...,  0.0311,  0.0249,  0.0167],
        ...,
        [-0.0081,  0.0194, -0.0266,  ..., -0.0269, -0.0002,  0.0257],
        [ 0.0202, -0.0002,  0.0831,  ..., -0.0008, -0.0094,  0.0258],
        [-0.0320,  0.0529, -0.0259,  ...,  0.0117, -0.0292, -0.0064]],
       requires_grad=True)


But if I use ``state_dict = torch.load('mp_rank_00_model_states.pt', map_location=torch.device('cpu')); model.load_state_dict(state_dict['module'])``, I get
(Pdb) model.deberta.encoder.layer[0].output.dense.weight
Parameter containing:
tensor([[-0.0211,  0.0068,  0.0206,  ...,  0.0057,  0.0316,  0.0256],
        [ 0.0273,  0.0141,  0.0118,  ..., -0.0122,  0.0054,  0.0010],
        [ 0.0479, -0.0237, -0.0604,  ..., -0.0340, -0.0183,  0.0691],
        ...,
        [ 0.0270, -0.0231,  0.0218,  ...,  0.0563,  0.0641, -0.0094],
        [-0.0563, -0.0837, -0.0427,  ...,  0.0242, -0.0132, -0.0512],
        [-0.0012,  0.0064,  0.0465,  ...,  0.0219,  0.0259, -0.0281]],
       requires_grad=True)

**Comment by skpig** [comment] 2021-09-25 02:44
@xycforgithub I have the same issue about loading checkpoint under multi-gpu and ZERO-2 setting. Do you have any methods to load it correctly ?

**Comment by stas00** [comment] 2021-09-25 02:50
I'm curious if you have tried with master, I was mainly doing fixes on zero3, but who knows perhaps something else got fixed on the way.

**Comment by xycforgithub** [comment] 2021-09-25 05:32
> @xycforgithub I have the same issue about loading checkpoint under multi-gpu and ZERO-2 setting. Do you have any methods to load it correctly ?

The only method under zero2 I find is to load the fp16 weights in mp_rank_00_model_states.pt.

**Comment by skpig** [comment] 2021-09-25 06:00
@stas00 I just updated my deepspeed to version 0.5.3 and tested the `load_state_dict_from_zero_checkpoint()`, but something went wrong.
```
Traceback (most recent call last):
  File "zero_to_fp32.py", line 375, in <module>
    convert_zero_checkpoint_to_fp32_state_dict(args.checkpoint_dir, args.output_file)
  File "zero_to_fp32.py", line 313, in convert_zero_checkpoint_to_fp32_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "zero_to_fp32.py", line 299, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "zero_to_fp32.py", line 244, in _get_fp32_state_dict_from_zero_checkpoint
    f"consumed {offset} numels out of {avail_numel} - something is wrong")
ValueError: consumed 255381772 numels out of 255381776 - something is wrong
```
Here is my code.
1. First I saved the model under ZeRO2 and 4 gpus settings . I used my own model class `MyBart` (subclass of transformers.BartPretrainedModel). 
```
    model = MyBart.from_pretrained("facebook/bart-base")
    param_optimizer = list(model.named_parameters())
    optimizer_grouped_parameters = [{
        'params':
            [p for n, p in param_optimizer],
        'weight_decay':
            0.01
    }]

    model_engine, optimizer, _, scheduler = deepspeed.initialize(args=args, model=model,
                                                                 model_parameters=optimizer_grouped_parameters)
    model_engine.save_checkpoint("Model/tmp", tag="ckpt")
    path, state = model_engine.load_checkpoint("Model/tmp", tag="ckpt")
```
2. Than I load the checkpoint without deepspeed, and the Error Message above happened.
```
    model = MyBart.from_pretrained("facebook/bart-base")
    print(model.lm_head.weight)
    print(model.si_lm_head.weight)
    print(model.base_model.encoder.layers[0].fc1.weight)
    model = load_state_dict_from_zero_checkpoint(model, "Model/tmp")
    print(model.lm_head.weight)
    print(model.si_lm_head.weight)
    print(model.base_model.encoder.layers[0].fc1.weight)
```

**Comment by stas00** [comment] 2021-09-25 06:10
please re-test with deepspeed@master - a few bug fixes were merged this week. Please report back if the problem has been resolved or not - thank you!

**Comment by stas00** [comment] 2021-09-25 06:15
> ValueError: consumed 255381772 numels out of 255381776 - something is wrong

The diff is 4 bytes, so this looks like the new padding introduced by Z2 recently. this code is a suspect:

https://github.com/microsoft/DeepSpeed/blob/c1829c45851eb1988684c9a2f4fd054ebd446b95/deepspeed/utils/zero_to_fp32.py#L226-L234

Perhaps I got the new padding wrong? Does the model work if you remove the assert?

**Comment by stas00** [comment] 2021-09-25 06:21
Here is the PR where I was trying to fix it https://github.com/microsoft/DeepSpeed/pull/1372
and here is the test that was reproducing the 2 bytes off problem:
https://github.com/microsoft/DeepSpeed/blob/c1829c45851eb1988684c9a2f4fd054ebd446b95/tests/unit/test_zero.py#L164

**Comment by stas00** [comment] 2021-09-25 06:22
Finally please run the script with `-d` so that we can see which params shapes you got (or enabled debug hardcoding in the script) if you're using the API.

**Comment by skpig** [comment] 2021-09-25 07:52
@stas00 Thanks for your reply. I'm so sorry for my misunderstanding about master & release version. I'm new to GitHub, please forgive me.
> please re-test with deepspeed@master - a few bug fixes were merged this week. Please report back if the problem has been resolved or not - thank you!
I retested the code with master branch. The Value Error (consumed 255381772 numels out of 255381776 - something is wrong) still happened. Then I do the testing following your instruction.
1. I removed the assert, and the loading process went well. I also randomly sampled some parameters to compare with original model. Only found 2 different values with error less than 0.0001. 
2. Then I added the code in the script as you told, and output `consumed 255381771 numels out of 255381775 `
> i.e. if you print out `f"consumed {offset} numels out of {avail_numel}"` before this line:
3. I ran the script with `-d`, and here is the output ( I skip the shapes of my model params because it is too long)
```
Found buffers: []
fp32_flat_groups[i].shape=torch.Size([63845444])
fp32_flat_groups[i].shape=torch.Size([63845444])
fp32_flat_groups[i].shape=torch.Size([63845444])
fp32_flat_groups[i].shape=torch.Size([63845443])
Have 255381775 numels to process.
Need 255381771 numels in 265 params.
added 0 buffers
```

**Comment by stas00** [comment] 2021-09-25 15:19
> @stas00 Thanks for your reply. I'm so sorry for my misunderstanding about master & release version. I'm new to GitHub, please forgive me.

Well, it's I who should ask for forgiveness since I made the assumption are you an old time user without checking in with you first :)

I'm glad you have figured it out on your own, @skpig  

> > please re-test with deepspeed@master - a few bug fixes were merged this week. Please report back if the problem has been resolved or not - thank you!
> 
> I retested the code with master branch. The Value Error (consumed 255381772 numels out of 255381776 - something is wrong) still happened. Then I do the testing following your instruction.
> 
>     1. I removed the assert, and the loading process went well. I also randomly sampled some parameters to compare with original model. Only found 2 different values with error less than 0.0001.
> 
>     2. Then I added the code in the script as you told, and output `consumed 255381771 numels out of 255381775 `
> 
> > i.e. if you print out `f"consumed {offset} numels out of {avail_numel}"` before this line:
> 
>     1. I ran the script with `-d`, and here is the output ( I skip the shapes of my model params because it is too long)
> 
> 
> ```
> Found buffers: []
> fp32_flat_groups[i].shape=torch.Size([63845444])
> fp32_flat_groups[i].shape=torch.Size([63845444])
> fp32_flat_groups[i].shape=torch.Size([63845444])
> fp32_flat_groups[i].shape=torch.Size([63845443])
> Have 255381775 numels to process.
> Need 255381771 numels in 265 params.
> added 0 buffers
> ```

Right, so I actually wanted to see the param shapes. You can always attach those to your comment as a file.

But even from the report above it's clear that the issue is of a padding and it's strange that your saved model is uneven.

So the next step is to be able to reproduce this for me. Could you try to dramatically reduce this model to say 2 layers and see if you could still reproduce the issue?

And ideally we want a public model since I don't know what is inside your `MyBart` - do you get the same issue if you use `Bart` instead.

To clarify this is clearly some edge case, so we need to reproduce and understand what's on the edge and then we should be able to fix if easily.

**Comment by stas00** [comment] 2021-09-25 15:22
p.s. there is another trick to including a huge log file in the comment and making it collapsible, see: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab#gistcomment-3899835

**Comment by stas00** [comment] 2021-09-25 15:41
And until this is sorted out if fp16 weights are enough under Z2 it's trivial to get those using this method:
https://huggingface.co/transformers/master/main_classes/deepspeed.html#getting-the-model-weights-out

**Comment by skpig** [comment] 2021-09-26 02:52
@stas00 Thanks for your instruction. I do the following test and hope it may help you reproduce the bug.
1. I use the `BartPretrainedModel` class (which `MyBart` subclass), and everything works well. So I guess probably it is the way I implement `MyBart` that produce the error.
2. I reduce this model to 2 layers and the error still exists.
    <details>
        <summary> code of <code>MyBart</code> </summary>
      
        
        class MyBart(BartPretrainedModel):
            def __init__(self, config: BartConfig):
                super().__init__(config)
                self.model = BartModel(config)
                self.lm_head = nn.Linear(config.d_model, self.model.shared.num_embeddings, bias=True)
                self.si_lm_head = nn.Linear(config.d_model, self.model.shared.num_embeddings, bias=True)
                self.dg_lm_head = nn.Linear(config.d_model, self.model.shared.num_embeddings, bias=True)
                self._init_weights(self.si_lm_head)
                self._init_weights(self.dg_lm_head)
                self._init_weights(self.lm_head)
        

    </details>
    <details>
        <summary> output of <code>zero_to_fp32.py</code> </summary>

        
        Processing zero checkpoint './ckpt'
        Detected checkpoint of type zero stage 2, world_size: 4
        Found buffers: []
        fp32_flat_groups[i].shape=torch.Size([43170884])
        fp32_flat_groups[i].shape=torch.Size([43170884])
        fp32_flat_groups[i].shape=torch.Size([43170884])
        fp32_flat_groups[i].shape=torch.Size([43170883])
        Have 172683535 numels to process.
        Need 172683531 numels in 55 params.
        added 0 buffers
        model.shared.weight full shape: torch.Size([50265, 768]) unpartitioned numel 38603520 
        model.encoder.embed_positions.weight full shape: torch.Size([1026, 768]) unpartitioned numel 787968 
        model.encoder.layers.0.self_attn.k_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.encoder.layers.0.self_attn.k_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.self_attn.v_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.encoder.layers.0.self_attn.v_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.self_attn.q_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.encoder.layers.0.self_attn.q_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.self_attn.out_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.encoder.layers.0.self_attn.out_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.self_attn_layer_norm.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.self_attn_layer_norm.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.fc1.weight full shape: torch.Size([3072, 768]) unpartitioned numel 2359296 
        model.encoder.layers.0.fc1.bias full shape: torch.Size([3072]) unpartitioned numel 3072 
        model.encoder.layers.0.fc2.weight full shape: torch.Size([768, 3072]) unpartitioned numel 2359296 
        model.encoder.layers.0.fc2.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.final_layer_norm.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layers.0.final_layer_norm.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layernorm_embedding.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.encoder.layernorm_embedding.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.embed_positions.weight full shape: torch.Size([1026, 768]) unpartitioned numel 787968 
        model.decoder.layers.0.self_attn.k_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.self_attn.k_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.self_attn.v_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.self_attn.v_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.self_attn.q_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.self_attn.q_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.self_attn.out_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.self_attn.out_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.self_attn_layer_norm.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.self_attn_layer_norm.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn.k_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.encoder_attn.k_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn.v_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.encoder_attn.v_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn.q_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.encoder_attn.q_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn.out_proj.weight full shape: torch.Size([768, 768]) unpartitioned numel 589824 
        model.decoder.layers.0.encoder_attn.out_proj.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn_layer_norm.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.encoder_attn_layer_norm.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.fc1.weight full shape: torch.Size([3072, 768]) unpartitioned numel 2359296 
        model.decoder.layers.0.fc1.bias full shape: torch.Size([3072]) unpartitioned numel 3072 
        model.decoder.layers.0.fc2.weight full shape: torch.Size([768, 3072]) unpartitioned numel 2359296 
        model.decoder.layers.0.fc2.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.final_layer_norm.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layers.0.final_layer_norm.bias full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layernorm_embedding.weight full shape: torch.Size([768]) unpartitioned numel 768 
        model.decoder.layernorm_embedding.bias full shape: torch.Size([768]) unpartitioned numel 768 
        lm_head.weight full shape: torch.Size([50265, 768]) unpartitioned numel 38603520 
        lm_head.bias full shape: torch.Size([50265]) unpartitioned numel 50265 
        si_lm_head.weight full shape: torch.Size([50265, 768]) unpartitioned numel 38603520 
        si_lm_head.bias full shape: torch.Size([50265]) unpartitioned numel 50265 
        dg_lm_head.weight full shape: torch.Size([50265, 768]) unpartitioned numel 38603520 
        dg_lm_head.bias full shape: torch.Size([50265]) unpartitioned numel 50265 
        
        Traceback (most recent call last):
          File "zero_to_fp32.py", line 366, in <module>
            convert_zero_checkpoint_to_fp32_state_dict(args.checkpoint_dir, args.output_file)
          File "zero_to_fp32.py", line 304, in convert_zero_checkpoint_to_fp32_state_dict
            state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
          File "zero_to_fp32.py", line 290, in get_fp32_state_dict_from_zero_checkpoint
            return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
          File "zero_to_fp32.py", line 235, in _get_fp32_state_dict_from_zero_checkpoint
            f"consumed {offset} numels out of {avail_numel} - something is wrong")
        ValueError: consumed 172683532 numels out of 172683536 - something is wrong
        

    </details>

**Comment by stas00** [comment] 2021-09-26 05:34
Thank you for that follow up, @skpig 

Most likely it hits some edge case due to your uneven vocab of 50265 - if you were to extend it to 50268 or shorten to 50264, I'm pretty sure the problem will go away.

So we need to write a small reproducible case that mimics your case and then it should be easy to fix I think.

The base test is already there if you'd like to fiddle with it, you run it as:

```
pyt --forked tests/unit/test_zero.py -k test_zero_to_fp32[2] -sv
```

Currently it passes with master and the idea is to change the model so that it breaks.

I will be able to look at it next week, unless you'd like to see if you can break this test by tweaking the dimensions/adding layers to emulate your sub-class.

The model to tweak is here:

https://github.com/microsoft/DeepSpeed/blob/c1829c45851eb1988684c9a2f4fd054ebd446b95/tests/unit/test_zero.py#L172-L176

and the test to run I shared above. 

Again, if it feels too complicated, I will look at it next week.

**Comment by skpig** [comment] 2021-09-29 01:45
@stas00 Sorry for the last response. I tried to tweak the model as below to reproduce the total model params of 50265. 
```
@distributed_test(world_size=[2])
def _test_zero_to_fp32():
    class MyModel(torch.nn.Module):
        def __init__(self, hidden_dim, n_layers):
            super().__init__()
            # to reproduce https://github.com/microsoft/DeepSpeed/pull/1372 it is important that
            # the number of total elements is uneven:
            # (1) 4188 layers of 3*(3+1)=12 elements each, 50256 in total
            self.ll = torch.nn.ModuleList(
                torch.nn.Linear(hidden_dim,
                                hidden_dim) for i in range(n_layers))
            # (2) the following adds 8+1=9 elements
            self.classifier = torch.nn.Linear(8, 1)
            # total 50256 + 9 = 50265 (uneven as desired) elements
            self.cross_entropy_loss = torch.nn.CrossEntropyLoss()

        def forward(self, x, y):
            hidden = x
            for l in self.ll:
                hidden = l(hidden)
            return self.cross_entropy_loss(hidden, y)

    args = args_from_dict(tmpdir, config_dict)
    hidden_dim = 3  # do not change

    world_size = dist.get_world_size()
    # we want at least 2x layers as there are gpus to trigger round_robin_fp16_groups reshuffle in zero2
    n_layers = world_size * 2094 # total 4188 layers

```
And ran the test as you told. It seemed that the test failed 

> `pyt --forked tests/unit/test_zero.py -k test_zero_to_fp32[2] -sv`
```
tests/unit/test_zero.py::test_zero_to_fp32[2] FAILED

===================================================================================== FAILURES ======================================================================================
_______________________________________________________________________________ test_zero_to_fp32[2] ________________________________________________________________________________
Worker 0 exited with code 1
============================================================================== short test summary info ==============================================================================
FAILED tests/unit/test_zero.py::test_zero_to_fp32[2]
========================================================================= 1 failed, 10 deselected in 35.30s =========================================================================
```

**Comment by skpig** [comment] 2021-09-29 02:56
I also pull the most recent commit (39c7744) and run the test. It seems like the current master can't pass the test either.

**Comment by stas00** [comment] 2021-09-30 02:36
Thank you for sending back the results, @skpig 

Excellent job on modifying the test!

It's odd, but your test works for me.

2 questions:

1. did this test work before you apply your changes - i.e. on a clean master.
2. what's the traceback for the failure you get with your change.

Meanwhile I will try to see if I can find some shape that can trigger a boundary issue.

**Comment by stas00** [comment] 2021-10-01 03:46
@skpig, please try this PR and let me know if it solves the problem on your side: https://github.com/microsoft/DeepSpeed/pull/1422

If you're not sure how to test a PR branch for your ease I attached the updated script (just rename it to have .py instead of .txt):
[zero_to_fp32.txt](https://github.com/microsoft/DeepSpeed/files/7263977/zero_to_fp32.txt)

Please let me know.

**Comment by stas00** [comment] 2021-10-01 06:31
@xycforgithub, most likely the bug you run into is with having multiple param groups under z2, correct?

If so we are trying to sort it out here: https://github.com/microsoft/DeepSpeed/issues/1412

**Comment by skpig** [comment] 2021-10-01 15:06
@stas00 
I'm sorry that I may have made a mistake. 
1. As I previously commented (https://github.com/microsoft/DeepSpeed/issues/1317#issuecomment-929753367), the test failed with my code tweaking the model params. And the test also failed with clean code as I mentioned (https://github.com/microsoft/DeepSpeed/issues/1317#issuecomment-929783068).
2. But the `-sv` args doesn't print any traceback information, so at that time I didn't realize what caused the failure. Now I try the `-v` args and print the traceback message as follow. It seems related to some permission error instead of the DeepSpeed's bug.
```
Traceback (most recent call last):                                                                                                                                                   
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                             
    self.run()                                                                                                                                                                       
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/multiprocessing/process.py", line 93, in run                                                                                     
    self._target(*self._args, **self._kwargs)                                                                                                                                        
  File "/home/huangbz/git_repo/DeepSpeed/tests/unit/common.py", line 53, in dist_init                                                                                                
    run_func(*func_args, **func_kwargs)                                                                                                                                              
  File "/home/huangbz/git_repo/DeepSpeed/tests/unit/test_zero.py", line 196, in _test_zero_to_fp32
    model_parameters=model.parameters())
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/__init__.py", line 141, in initialize
    config_params=config_params)
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/runtime/engine.py", line 220, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/runtime/engine.py", line 860, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/runtime/engine.py", line 942, in _configure_basic_optimizer
    adam_w_mode=effective_adam_w_mode)
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/ops/op_builder/builder.py", line 355, in load
    return self.jit_load(verbose)
  File "/home/huangbz/git_repo/DeepSpeed/deepspeed/ops/op_builder/builder.py", line 380, in jit_load
    os.makedirs(ext_path, exist_ok=True)
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/fused_adam'
```
3. I'm now testing the PR, I'll reply to you as soon as possible.

**Comment by xycforgithub** [comment] 2021-10-01 18:15
> @xycforgithub, most likely the bug you run into is with having multiple param groups under z2, correct?
> 
> If so we are trying to sort it out here: #1412

Yes I can verify that my model also has multiple param groups under z2. Thank you for the pointer!

**Comment by stas00** [comment] 2021-10-01 18:26
Great, please try this PR then: https://github.com/microsoft/DeepSpeed/pull/1424 and comment there if it solves the problem for you. Thank you!

**Comment by skpig** [comment] 2021-10-02 01:29
@stas00 The PR #1422 has solved my problem. The model loaded well and reconstructed fp32 value correctly. Thank you !!!

**Comment by stas00** [comment] 2021-10-02 01:33
Awesome! Thank you for validating that, @skpig 

We will most likely have another iteration for you to check a bit later on, once https://github.com/microsoft/DeepSpeed/pull/1424 is integrated with z3.

**Comment by stas00** [comment] 2021-10-02 02:35
@skpig and @xycforgithub if you could both try https://github.com/microsoft/DeepSpeed/pull/1424 - it has a major rewrite of z2 reconstruction code by @eelxpeng

**Closed** 2021-10-04 17:44 UTC
