### ISSUE TITLE
Does AMD CPU support cpu_adam? DS_BUILD_CPU_ADAM=1 causes compilation error

### ISSUE THREAD

**Issue by winkzy** [microsoft/DeepSpeed#788] opened 2021-02-24 18:07 UTC
```python
        if 'genuineintel' in result:
            if 'avx512' in result:
                return '-D__AVX512__'
            elif 'avx2' in result:
                return '-D__AVX256__'
        return ''
```
https://github.com/microsoft/DeepSpeed/blob/e60e92eb0a06673748c4cb63fbcf713ddd12fc22/op_builder/cpu_adam.py#L39

Hardware: 2 * AMD 7742 + HGX-A100-8GPU
Software: CentOS 7.8, PyTorch 1.7.0+cu110, Apex, Triron 0.2.3

I built DeepSpeed from source:
``TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0" DS_BUILD_FUSED_ADAM=1 DS_BUILD_FUSED_LAMB=1 DS_BUILD_TRANSFORMER=1 DS_BUILD_STOCHASTIC_TRANSFORMER=1 DS_BUILD_UTILS=1 pip install .``

got following result:

```bash
$ ds_report 
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
```

but ``TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0" DS_BUILD_CPU_ADAM=1 pip install .`` failed

```bash
gcc "..." -c csrc/adam/cpu_adam.cpp -o build/temp.linux-x86_64-3.6/csrc/adam/cpu_adam.o "..."
gcc: error: : No such file or directory
```

Is "GenuineIntel" a necessary check? Or add "AuthenticAMD"

**Comment by RezaYazdaniAminabadi** [comment] 2021-02-26 05:03
Hi @winkzy 

Thanks for reporting this issue. 
I could repro the same issue on an A100 node and have pushed a fix for it. The issue is that none of the AVX capabilities are supported on AMD machines for now. So, we can only use scalar mode. However, we have plan to add the vector implementation for AMD architecture as well. 
Regarding the performance, we still see 5x speedup as experimented before in this [PR](https://github.com/microsoft/DeepSpeed/pull/735).
Could you please give this fix a try and see if the issue is solved?
Thanks,
Reza

**Comment by winkzy** [comment] 2021-02-26 14:26
> Hi @winkzy
> 
> Thanks for reporting this issue.
> I could repro the same issue on an A100 node and have pushed a fix for it. The issue is that none of the AVX capabilities are supported on AMD machines for now. So, we can only use scalar mode. However, we have plan to add the vector implementation for AMD architecture as well.
> Regarding the performance, we still see 5x speedup as experimented before in this [PR](https://github.com/microsoft/DeepSpeed/pull/735).
> Could you please give this fix a try and see if the issue is solved?
> Thanks,
> Reza

Thanks a lot. 
If the AMD CPU cannot be supported for now, I suggest that it can give a warning, such as ``[WARNING]  cpu_adam requires Intel cpu, does not currently support AMD cpu ``.
We are now using the AMD+HGX-A100 hardware, and look forward to following support.

**Comment by RezaYazdaniAminabadi** [comment] 2021-02-26 16:32
This is not that it does not support AMD CPU. As I mentioned in the previous comment, it works well on AMDs and actually outperforms torch adam, however, it is not working with the full features.
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment] 2021-02-26 16:38
Here are some stats for the performance on AMD machines:
https://github.com/microsoft/DeepSpeed/pull/735#issuecomment-775452878

**Closed** 2021-02-26 18:25 UTC

**Comment by winkzy** [comment] 2021-02-28 08:58
> Here are some stats for the performance on AMD machines:
> [#735 (comment)](https://github.com/microsoft/DeepSpeed/pull/735#issuecomment-775452878)

Thanks a lot.
