### ISSUE TITLE
[BUG] Zero-Inference usage error with .init_inference()

### ISSUE THREAD

**Issue by joaopcm1996** [microsoft/DeepSpeed#2372] opened 2022-09-28 15:23 UTC
**Describe the bug**
Passing Zero level-3 cpu offload parameters to the `args` parameter of .init_inference() does not have any effect, still consuming all GPU memory for a large model and throwing an error. 

Following the [blog post](https://www.deepspeed.ai/2022/09/09/zero-inference.html) on Zero-Inference, I tried to load a GPT-J model with DeepSpeed Inference, and got a CUDA OOM error.

How should I pass in the deepspeed config parameters to the init_inference method? Or should  I just .initialize() even if using the model for inference?

**To Reproduce**
```

import os, torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import deepspeed

model_name = "EleutherAI/gpt-j-6B"

model = AutoModelForCausalLM.from_pretrained(
    model_name, revision="float32", torch_dtype=torch.float32
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

deepspeed_config = {
        "zero_optimization": {
        "stage": 3,
        "offload_param": {
            "device": "cpu"
        },
    }
}

model = deepspeed.init_inference(
    model,
    args=deepspeed_config,
    dtype=model.dtype,
    replace_method="auto",
    replace_with_kernel_inject=True,
)
```

Error :

`RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 14.56 GiB total capacity; 13.52 GiB already allocated; 52.44 MiB free; 13.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Expected behavior**
The first layer of the model being loaded , and then layers dynamically loaded as they are needed for inference.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
which: no hipcc in (/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/home/ec2-user/anaconda3/condabin:/home/ec2-user/.dl_binaries/bin:/opt/aws/neuron/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin:/home/ec2-user/anaconda3/condabin:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/home/ec2-user/anaconda3/condabin:/home/ec2-user/.dl_binaries/bin:/opt/aws/neuron/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/torch']
torch version .................... 1.5.1
torch cuda version ............... 10.2
torch hip version ................ None
nvcc version ..................... 11.0
deepspeed install path ........... ['/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.7.3, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.5, cuda 10.2
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Amazon LInux 2
 - 1 machine (g4dn.8xlarge on Amazon Sagemaker with 1 Tesla T4 GPU)
 - Transformers version=4.22.2
 - Python version=3.8.12

**Comment by tjruwase** [comment] 2022-09-28 16:05
@joaopcm1996, thanks for reporting this issue and apologies for the confusion. ZeRO-Inference requires
1. Using zero.Init() context manager for model construction as documented [here](https://deepspeed.readthedocs.io/en/latest/zero3.html#constructing-massive-models). 
2. The `deepspeed.initialize()` to construct the DeepSpeed engine. Note that you should not pass an optimizer. 

You might find the zero-inference script for BLOOM-176b useful: [bloom-ds-zero-inference.py](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py)

**Comment by lokoppakmsft** [comment] 2022-10-12 20:04
@joaopcm1996 I confirmed that following the steps indicated by @tjruwase and implementing inference script similar to [hugging face bloom example](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py) I can use zero inference. 

Please let us know if the issue is resolved and if we can close this issue.

**Comment by jeffra** [comment] 2022-10-13 21:10
@joaopcm1996, please re-open if this is still an issue.

**Closed by jeffra** 2022-10-13 21:10 UTC
Labels: bug, inference

**Comment by joaopcm1996** [comment] 2022-10-14 06:51
@lokoppakmsft  thanks a lot for testing it and sorry for the delayed response. I will test it myself, if there is any issue I will refer back here as @jeffra suggested.

**Comment by lambda7xx** [comment] 2023-02-24 09:19
> @joaopcm1996, please re-open if this is still an issue.

- hi, sorry to bother you. I use the [bloom-ds-zero-inference.py](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py) . It is two slow.

Below is my code 
'''
# usage:
# deepspeed --num_gpus 8 bloom-ds-zero-inference.py --name bigscience/bloom
#
# to run benchmarks:
# deepspeed --num_gpus 8 bloom-ds-zero-inference.py --name bigscience/bloom --benchmark
#


# This is going to improve, but at the moment, the process is a bit cumbersome - we first use
# 1. use Deepspeed-ZeRO to instantiate the model on GPUs, w/o loading the checkpoints,
# 2. free the allocated storage
# 3. start Deepspeed-Inference and only now load the checkpoint
# 4. run generate
# Done.
#


import gc
import math
import os
import time
from argparse import ArgumentParser

import torch
import torch.distributed as dist

import deepspeed
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
from transformers.deepspeed import HfDeepSpeedConfig
from transformers.models.bloom.modeling_bloom import BloomBlock as BloomBlock


t_start = time.time()

num_tokens = 50

parser = ArgumentParser()

parser.add_argument("--name", required=True, type=str, help="model_name")
parser.add_argument("--local_rank", required=False, type=int, help="used by dist launchers")
parser.add_argument("--batch_size", default=1, type=int, help="batch size")
parser.add_argument("--benchmark", action="store_true", help="additionally run benchmark")
parser.add_argument("--cpu_offload", action="store_true", help="whether to activate CPU offload")
parser.add_argument("--nvme_offload_path", help="whether to activate NVME offload and the path on nvme")
args = parser.parse_args()

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

deepspeed.init_distributed("nccl")
rank = dist.get_rank()


def print_rank0(*msg):
    if rank != 0:
        return
    print(*msg)


### Model loading and instantiating on GPU (via ZeRO)

model_name = args.name

print_rank0(f"*** Loading the model {model_name}")

"""
            self.config = AutoConfig.from_pretrained(self.model_name)
            self.repo_root, self.checkpoints_json = self._generate_json(checkpoint_path)

            with deepspeed.OnDevice(dtype=torch.float16, device="meta"):
                self.model = AutoModelForCausalLM.from_config(self.config)
"""

tokenizer = AutoTokenizer.from_pretrained(model_name)
config = AutoConfig.from_pretrained(model_name)

# XXX: can't automatically derive dtype via config's `from_pretrained`
dtype = torch.bfloat16 if model_name in ["bigscience/bloom", "bigscience/bigscience-small-testing"] else torch.float16

model_hidden_size = config.hidden_size
train_batch_size = 1 * world_size

ds_config = {
    "fp16": {
        "enabled": dtype == torch.float16,
    },
    "bf16": {
        "enabled": dtype == torch.bfloat16,
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": model_hidden_size * model_hidden_size,
        "stage3_prefetch_bucket_size": 0.9 * model_hidden_size * model_hidden_size,
        "stage3_param_persistence_threshold": 0,
    },
    "steps_per_print": 2000,
    "train_batch_size": train_batch_size,
    "train_micro_batch_size_per_gpu": 1,
    "wall_clock_breakdown": False,
}

if args.cpu_offload and args.nvme_offload_path:
    raise ValueError("Use one of --cpu_offload or --nvme_offload_path and not both")

if args.cpu_offload:
    ds_config["zero_optimization"]["offload_param"] = dict(device="cpu", pin_memory=True)

if args.nvme_offload_path:
    ds_config["zero_optimization"]["offload_param"] = dict(
        device="nvme",
        pin_memory=True,
        nvme_path=args.nvme_offload_path,
        buffer_size=4e9,
    )

dschf = HfDeepSpeedConfig(ds_config)  # this tells from_pretrained to instantiate directly on gpus

if args.benchmark:
    torch.cuda.empty_cache()
    gc.collect()
    deepspeed.runtime.utils.see_memory_usage("pre-from-pretrained", force=True)


with deepspeed.OnDevice(dtype=torch.bfloat16, device="meta"):
    model = AutoModelForCausalLM.from_config(config)
# model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16)

if args.benchmark:
    deepspeed.runtime.utils.see_memory_usage("post-from-pretrained", force=True)

model = model.eval()

print_rank0(ds_config)

ds_engine = deepspeed.initialize(model=model, config_params=ds_config)[0]
ds_engine.module.eval()
model = ds_engine.module

if args.benchmark:
    t_ready = time.time()
    deepspeed.runtime.utils.see_memory_usage("start-of-generate", force=True)


### Generate

print_rank0(f"*** Starting to generate {num_tokens} tokens with bs={args.batch_size}")

input_sentences = [
         "DeepSpeed is a machine learning framework",
         "He is working on",
         "He has a",
         "He got all",
         "Everyone is happy and I can",
         "The new movie that got Oscar this year",
         "In the far far distance from our galaxy,",
         "Peace is the only way",
         "Shanghai Jiao Tong University is a famous university ",#9
         "I Love UC Berkeley because it's ", #10
         "Paris is the captial of France and ",#11
         "History is very interesting," , #12 
         "It is the tears of the earth that keep here smiles in bloom", #13
         "If you shed tears when you miss the sun, you also miss the stars.", #14
         "Her wishful face haunts my dreams like the rain at night.",#15
         "I cannot choose the best. The best chooses me.",#16
         "Anything in life worth doing is worth overdoing.",#17
         "Life is like a box of chocolates, you never know what you are going to get",#18
         ". It is up to you to give life a meaning.",#19
         "Machine learning models are becoming", #20
         "Prediction serving systems often employ distributed ",#21
         "The primary differences between coded-computation and the traditional code is "#22
        "With this observation in mind", #23
        "We evaluate Alpa on training large models",#24
        "DL computation is commonly represented",#25
        "With the growing model size, deep neural networks (DNN) are " ,#26
        "We thank all the anonymous reviewers for",#27
        "we discuss the advantages and several limitations of",#28
        "The Serverless Computing is becoming increasingly popular",#29
        "Our experiment analysis shows that",#30
        "Serverless computing, also known as Function-as-a-Service (FaaS),"#31
        "We investigate the limitations of",#32
        "To reduce data movement overhead ",#33
         "we first introduce ",#34
         "I like xinyi because she ", #35
        "DNN training is extremely time-consuming,",#36
        "To address these challenges",#37
        "To improve statistical efficiency, ",#38
        "MSRA is awesome", #39
        "I am happy because",#40
        "Our results show that, by decoupling memory and CPU allocation,",#41
        "Furthermore, we demonstrate that" ,#42 
        "Minimizing data movement is key to ",#43
        "Because there is no generic or reliable way  for",#44
        "This paper explores a novel point in the design space by ",#45
        "we start by discussing",#46 
        "Figure 1 shows the main components of", #47
        "A key goal of successful is ",#48
        "we focus on two broad ",#49
        "It is a scarce resource",#50
]

if args.batch_size > len(input_sentences):
    # dynamically extend to support larger bs by repetition
    input_sentences *= math.ceil(args.batch_size / len(input_sentences))

generate_kwargs = dict(max_new_tokens=num_tokens, do_sample=False)

print_rank0(f"Generate args {generate_kwargs}")
inputs = input_sentences[: args.batch_size]


def generate():
    """returns a list of zipped inputs, outputs and number of new tokens"""
    t0 = time.time()
    input_tokens = tokenizer.batch_encode_plus(inputs, return_tensors="pt", padding=True)#prompt 
    duration = time.time() -t0
    
    t0 = time.time()
    for t in input_tokens:
        if torch.is_tensor(input_tokens[t]):
            input_tokens[t] = input_tokens[t].to(torch.cuda.current_device())
    to_device_duration1 = time.time()-t0
    to = time.time()
    outputs = model.generate(**input_tokens, **generate_kwargs)#开始generate
    generate_duration = time.time() - to 
    input_tokens_lengths = [x.shape[0] for x in input_tokens.input_ids]
    output_tokens_lengths = [x.shape[0] for x in outputs]

    total_new_tokens = [o - i for i, o in zip(input_tokens_lengths, output_tokens_lengths)]
    t0 = time.time()
    outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)#list 
    decode_duration = time.time() - t0 
    if rank == 0:
        print("duration:",duration, " and len(total_new_tokens):",len(total_new_tokens), "and first new_token_length:",total_new_tokens[0], "to_device_duration:",to_device_duration1, " and generate duation:",generate_duration, " decode duation:",decode_duration)
    return zip(inputs, outputs, total_new_tokens),duration, input_tokens_lengths,output_tokens_lengths


# XXX: this is currently doing world_size streams on world_size gpus, so we can feed it different inputs on each! and hence the time can be divided by world_size

print_rank0("*** Running generate")
t_generate_start = time.time()
pairs, _, _, _  = generate()
t_generate_span = time.time() - t_generate_start
for i, o, _ in pairs:
    print_rank0(f"{'-'*60}\nin={i}\nout={o}\n")

if rank==0:
    print("t_generate_span:",t_generate_span)
### Benchmark

if args.benchmark:
    # clear cache / free memory
    torch.cuda.empty_cache()
    gc.collect()
    deepspeed.runtime.utils.see_memory_usage("end-of-generate", force=True)

    print_rank0("*** Running benchmark")

    # warm up
    for i in range(1):
        _ = generate()
    torch.cuda.synchronize()

    # benchmark
    t0 = time.time()
    cycles = 30
    total_new_tokens_generated = 0
    total_e2e_time = 0
    total_prompt_time = 0
    totoal_time = 0
    for i in range(cycles):
        e2e_start = time.time()
        generated,duration, input_tokens_lengths,output_tokens_lengths= generate()

        total_new_tokens_generated += sum(new_tokens for _, _, new_tokens in generated)
        totoal_time += time.time() - t0 
        e2e_duration = time.time() - e2e_start
        # if i == 0 or i == (cycles - 1):
        if rank == 0:
            print("e2e_duration:",e2e_duration, " and prompt duaration:",duration)
        total_e2e_time += e2e_duration
        total_prompt_time += duration
        if rank ==0 or i == (cycles-1):
            #print("")
            #print("helllo")
            for inputs, outputs,_ in generate:
                for i,o, i_len, o_len in zip(inputs,outputs,input_tokens_lengths,output_tokens_lengths):
                    print("\n\n")
                    print("len(i):",len(i), " and len(o):",len(o), "and new_token_length:",o_len - i_len  )
                    print(f"\nin={i}\nout={o}\n\n\n")

    torch.cuda.synchronize()
    # note that we actually generate world_size unique streams (though the benchmark feeds the same inputs)
    avg_e2e_time = total_e2e_time  / cycles 
    avg_prompt_time = total_prompt_time / cycles 
    if rank ==0:
        print("after cycles ",cycles, " the ave_e2e_time:",avg_e2e_time, " and avg_prompt_time:",avg_prompt_time)
    total_new_tokens_generated *= world_size
    throughput = (total_e2e_time) / (total_new_tokens_generated)
    print_rank0(
        f"""
*** Performance stats:
Throughput per token including tokenize: {throughput*1000:.2f} msecs
Start to ready to generate: {t_ready - t_start:.3f} secs
Tokenize and generate {total_new_tokens_generated} (bs={args.batch_size}) tokens: {t_generate_span:.3f} secs
Start to finish: {t_ready - t_start + t_generate_span:.3f} secs
"""
    )

'''

And I get the warning 
```
/home/lambda7xx/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(

```
The e2e generation time is about 2000 second. This is too slow.
