### ISSUE TITLE
RuntimeError: : Optimizer lost track of step count!

### ISSUE THREAD

**Issue by hujian233** [microsoft/DeepSpeed#562] opened 2020-11-26 06:26 UTC
When I tried to continue training from a model with 100 step checkpoints, I modify the scrpits `--train-iters ` from 100 to 1500 and 
add `--load checkpoints/gpt2_0.8B`  parameter which is consistent in the training process.  The checkpoint are loading success, but I got an error:
```
[2020-11-26 14:12:39,268] [INFO] [engine.py:1285:_load_checkpoint] rank: 1 loading checkpoint: checkpoints/gpt2_0.8B/100/mp_rank_01_model_states.pt
successfully loaded 2 ZeRO state_dicts for rank 0
successfully loaded 2 ZeRO state_dicts for rank 7
loading 2 zero partition checkpoints for rank 0
loading 2 zero partition checkpoints for rank 7
successfully loaded 2 ZeRO state_dicts for rank 4
successfully loaded 2 ZeRO state_dicts for rank 3
loading 2 zero partition checkpoints for rank 4
successfully loaded 2 ZeRO state_dicts for rank 5
successfully loaded 2 ZeRO state_dicts for rank 1
loading 2 zero partition checkpoints for rank 3
loading 2 zero partition checkpoints for rank 1
loading 2 zero partition checkpoints for rank 5
  successfully loaded checkpoints/gpt2_0.8B/100/mp_rank_01_model_states.pt
  successfully loaded checkpoints/gpt2_0.8B/100/mp_rank_00_model_states.pt
  successfully loaded checkpoints/gpt2_0.8B/100/mp_rank_03_model_states.pt
  successfully loaded checkpoints/gpt2_0.8B/100/mp_rank_02_model_states.pt
[2020-11-26 14:12:48,690] [INFO] [checkpointing.py:63:see_memory_usage] First Forward Begining
[2020-11-26 14:12:48,692] [INFO] [checkpointing.py:64:see_memory_usage] Memory Allocated 1.2926912307739258 GigaBytes
[2020-11-26 14:12:48,694] [INFO] [checkpointing.py:68:see_memory_usage] Max Memory Allocated 1.5387849807739258 GigaBytes
/opt/conda/lib/python3.8/site-packages/torch/cuda/memory.py:344: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
[2020-11-26 14:12:48,697] [INFO] [checkpointing.py:72:see_memory_usage] Cache Allocated 1.98828125 GigaBytes
/opt/conda/lib/python3.8/site-packages/torch/cuda/memory.py:352: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:76:see_memory_usage] Max cache Allocated 1.98828125 GigaBytes
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:357:forward] Activation Checkpointing Information
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:358:forward] ----Partition Activations True, CPU CHECKPOINTING True
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:361:forward] ----contiguous Memory Checkpointing True with 24 total layers
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:364:forward] ----Synchronization False
[2020-11-26 14:12:48,698] [INFO] [checkpointing.py:365:forward] ----Profiling False
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 717, in <module>
    main()
  File "pretrain_gpt2.py", line 689, in main
            main()main()    

main()main()  File "pretrain_gpt2.py", line 689, in main
  File "pretrain_gpt2.py", line 689, in main

  File "pretrain_gpt2.py", line 689, in main

          File "pretrain_gpt2.py", line 689, in main
main()    main()main()


  File "pretrain_gpt2.py", line 689, in main
  File "pretrain_gpt2.py", line 689, in main
  File "pretrain_gpt2.py", line 689, in main
    iteration, skipped = train(model, optimizer,
  File "pretrain_gpt2.py", line 413, in train
            iteration, skipped = train(model, optimizer,iteration, skipped = train(model, optimizer,iteration, skipped = train(model, optimizer,


  File "pretrain_gpt2.py", line 413, in train
  File "pretrain_gpt2.py", line 413, in train
  File "pretrain_gpt2.py", line 413, in train
        lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)iteration, skipped = train(model, optimizer,

  File "pretrain_gpt2.py", line 383, in train_step
  File "pretrain_gpt2.py", line 413, in train
    iteration, skipped = train(model, optimizer,
  File "pretrain_gpt2.py", line 413, in train
        iteration, skipped = train(model, optimizer,iteration, skipped = train(model, optimizer,

  File "pretrain_gpt2.py", line 413, in train
  File "pretrain_gpt2.py", line 413, in train
    lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)    
lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)      File "pretrain_gpt2.py", line 383, in train_step

lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)  File "pretrain_gpt2.py", line 383, in train_step

  File "pretrain_gpt2.py", line 383, in train_step
    lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)
  File "pretrain_gpt2.py", line 383, in train_step
    model.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
    lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)
  File "pretrain_gpt2.py", line 383, in train_step
    model.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
        model.step()model.step()

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
        lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)lm_loss, skipped_iter = train_step(train_data_iterator, model, optimizer, lr_scheduler, args, timers)

      File "pretrain_gpt2.py", line 383, in train_step
  File "pretrain_gpt2.py", line 383, in train_step
model.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
    model.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
        model.step()model.step()

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 973, in step
        self._take_model_step()self._take_model_step()

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
                self._take_model_step()self._take_model_step()self._take_model_step()self._take_model_step()



  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
        self._take_model_step()  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step

self._take_model_step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 928, in _take_model_step
    self.optimizer.step()
      File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
self.optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
    self.optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
    self.optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
        self.optimizer.step()self.optimizer.step()

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
        self.optimizer.step()self.optimizer.step()

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1417, in step
    self.optimizer.step(fp16_param_groups=fp16_param_groups)    
self.optimizer.step(fp16_param_groups=fp16_param_groups)    
self.optimizer.step(fp16_param_groups=fp16_param_groups)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
            self.optimizer.step(fp16_param_groups=fp16_param_groups)self.optimizer.step(fp16_param_groups=fp16_param_groups)self.optimizer.step(fp16_param_groups=fp16_param_groups)


  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
        self.optimizer.step(fp16_param_groups=fp16_param_groups)self.optimizer.step(fp16_param_groups=fp16_param_groups)

  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)        
        return func(*args, **kwargs)        return func(*args, **kwargs)return func(*args, **kwargs)  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
    return func(*args, **kwargs)
return func(*args, **kwargs)  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
return func(*args, **kwargs)

return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step


  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step

  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 117, in step
        self.ds_opt_adam.adam_update_copy(self.ds_opt_adam.adam_update_copy(
    
            self.ds_opt_adam.adam_update_copy(self.ds_opt_adam.adam_update_copy(RuntimeErrorself.ds_opt_adam.adam_update_copy(        self.ds_opt_adam.adam_update_copy(

: 
RuntimeErrorself.ds_opt_adam.adam_update_copy(self.ds_opt_adam.adam_update_copy(
Optimizer lost track of step count!
: 


RuntimeErrorRuntimeErrorRuntimeErrorOptimizer lost track of step count!
: 
RuntimeError: : Optimizer lost track of step count!
RuntimeErrorRuntimeError: : Optimizer lost track of step count!
Optimizer lost track of step count!

: Optimizer lost track of step count!
Optimizer lost track of step count!


Optimizer lost track of step count!
```
Does anybody know why that is?

**Comment by RezaYazdaniAminabadi** [comment] 2020-11-28 05:55
Hi @hujian233 

Thanks for reporting this issue. This is coming from the tracking issue of the cpu-adam optimizer step when you loaded the checkpoint from step 100. I pushed a fix in this PR: https://github.com/microsoft/DeepSpeed/pull/564
Please give it a try and let me know if the problem is solved. 

Thanks.
Reza

**Comment by hujian233** [comment] 2020-11-30 06:29
Hello ！@RezaYazdaniAminabadi  @jeffra ，my docker enviroment is cuda11 and pytorch1.7，I used `deepspeed/deepspeed:v034-jitops-torch170-cuda11` this image which is mention in [microsoft/DeepSpeed/issues/536]
I can modify the cpu_adam.h file, but I don't how to compile it. So it doesn't worked!
When I use the  just-in-time (JIT) ，it will report the following error:

```
Using /root/.cache/torch_extensions as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/cpu_adam...
Using /root/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -I/opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -gencode arch=compute_86,code=compute_86 -c /opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/custom_cuda_kernel.cu -o custom_cuda_kernel.cuda.o 
FAILED: custom_cuda_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -I/opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -gencode arch=compute_86,code=compute_86 -c /opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/custom_cuda_kernel.cu -o custom_cuda_kernel.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_86'

...
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 728, in <module>
    main()
  File "pretrain_gpt2.py", line 676, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 170, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 109, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 181, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 590, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 655, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 70, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 156, in load
    return self.jit_load(verbose)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 184, in jit_load
    op_module = load(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 969, in load
    return _jit_compile(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1543, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/opt/conda/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'cpu_adam'

```

**Comment by RezaYazdaniAminabadi** [comment] 2020-12-03 01:11
Hi @hujian233 

We have already solved the issue for the CPU-Adam with loading the checkpointing in the github branch. For the compilation issue, @jeffra just pushed this PR (https://github.com/microsoft/DeepSpeed/pull/572) that will solve it too. Could you please check in the updated code when it's merged and try this again?

Thanks,
Reza

**Comment by jeffra** [comment] 2020-12-03 01:24
#572 is merged now. Please give it a try when you can @hujian233

**Closed** 2024-09-09 19:02 UTC
