### ISSUE TITLE
[BUG] Encountered a problem when using SparseSelfAttention.

### ISSUE THREAD

**Issue by AngThanos** [microsoft/DeepSpeed#1460] opened 2021-10-19 13:27 UTC
Hi there,

I attempt to use SparseSelfAttention class to calculate matrix multiplication as following code:
result_layer = self.sparse_self_attention(query_layer,
                                                   key_layer,
                                                   value_layer,
                                                   key_padding_mask=None)
Two months ago, the thing was oke but now I run the same code again and an error is triggered as shown below:
ImportError: cannot import name 'MatMul' from 'deepspeed.ops.sparse_attention' (/usr/local/lib/python3.7/dist-packages/deepspeed/ops/sparse_attention/__init__.py)

Please help me fix that error.
Many thanks!

P/s: Deepspeed was successfully installed via ds_report.txt.
[ds_report.txt](https://github.com/microsoft/DeepSpeed/files/7373631/ds_report.txt)

**Comment by RezaYazdaniAminabadi** [comment] 2021-10-29 19:26
Hi @AngThanos,

this problem might be due to the changes we imported from the new version of Triton. I will try this and let you know if I repro this. If you could provide me some test for this, that would be awesome. 
We will push a fix for this soon.
Thanks,
Reza

**Comment by shehan360** [comment] 2022-04-05 00:12
Hi Im having the same error when I try
`from deepspeed.ops.sparse_attention import MatMul, Softmax`

The error - 
`ImportError: cannot import name 'MatMul' from 'deepspeed.ops.sparse_attention' (/opt/conda/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/__init__.py)`

my 'ds_report' is:

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.7/site-packages/torch']
torch version .................... 1.11.0
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/opt/conda/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.6.2+0149bd4f, 0149bd4f, master
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3, hip 0.0
```

**Comment by shehan360** [comment] 2022-04-05 01:31
> Hi Im having the same error when I try `from deepspeed.ops.sparse_attention import MatMul, Softmax`
> 
> The error - `ImportError: cannot import name 'MatMul' from 'deepspeed.ops.sparse_attention' (/opt/conda/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/__init__.py)`
> 
> my 'ds_report' is:
> 
> ```
> --------------------------------------------------
> DeepSpeed C++/CUDA extension op report
> --------------------------------------------------
> NOTE: Ops not installed will be just-in-time (JIT) compiled at
>       runtime if needed. Op compatibility means that your system
>       meet the required dependencies to JIT install the op.
> --------------------------------------------------
> JIT compiled ops requires ninja
> ninja .................. [OKAY]
> --------------------------------------------------
> op name ................ installed .. compatible
> --------------------------------------------------
> cpu_adam ............... [NO] ....... [OKAY]
> cpu_adagrad ............ [NO] ....... [OKAY]
> fused_adam ............. [NO] ....... [OKAY]
> fused_lamb ............. [NO] ....... [OKAY]
> sparse_attn ............ [YES] ...... [OKAY]
> transformer ............ [NO] ....... [OKAY]
> stochastic_transformer . [NO] ....... [OKAY]
> async_io ............... [NO] ....... [OKAY]
> utils .................. [NO] ....... [OKAY]
> quantizer .............. [NO] ....... [OKAY]
> transformer_inference .. [NO] ....... [OKAY]
> --------------------------------------------------
> DeepSpeed general environment info:
> torch install path ............... ['/opt/conda/lib/python3.7/site-packages/torch']
> torch version .................... 1.11.0
> torch cuda version ............... 11.3
> torch hip version ................ None
> nvcc version ..................... 11.3
> deepspeed install path ........... ['/opt/conda/lib/python3.7/site-packages/deepspeed']
> deepspeed info ................... 0.6.2+0149bd4f, 0149bd4f, master
> deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3, hip 0.0
> ```

This was due to a wrong import. The correct import is.

` from deepspeed.ops.sparse_attention.matmul import MatMul`

**Comment by loadams** [comment] 2023-08-22 16:52
Closing as the issue is stale given the updates to DeepSpeed and triton.

**Closed by loadams** 2023-08-22 16:52 UTC
Labels: bug
