### ISSUE TITLE
[BUG] Missing arguments in InferenceEngine

### ISSUE THREAD

**Issue by sunyt32** [microsoft/DeepSpeed#2330] opened 2022-09-17 12:35 UTC
**Describe the bug**
When I init inference engine with checkpoint file, the code will fail due to the argument 'checkpoint_engine' isn't passed correctly. 
https://github.com/microsoft/DeepSpeed/blob/15923810182c47fd95be2991babd764ddad3c74f/deepspeed/inference/engine.py#L407

**Comment by RezaYazdaniAminabadi** [comment] 2022-09-20 16:09
Hi @sunyt32 

Can you please give me a script to reproduce this?
Thanks,
Reza

**Comment by sunyt32** [comment] 2022-09-22 14:50
``
import deepspeed
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
from transformers.models.bloom.modeling_bloom import BloomBlock as BloomBlock

parser = argparse.ArgumentParser()
# Model setting
parser.add_argument('--model', type=str, default="bloom-deepspeed-inference-fp16")
# Distributed setting
parser.add_argument("--local_rank", required=False, type=int, help="used by dist launchers")
# Data setting
parser.add_argument('--task', type=str)
parser.add_argument('--data_path', type=str, default="./data")
parser.add_argument('--log_path', type=str)
# Parameters
parser.add_argument('--repeat_num', type=int, default=5)
parser.add_argument('--max_length', type=int, default=2000)
parser.add_argument('--chunk_num', type=int, default=1)
args = parser.parse_args()

init_distributed_mode(args)
model_path = os.path.join(args.data_path, "model", args.model)

tokenizer = AutoTokenizer.from_pretrained(
    model_path, 
    use_fast=False)
config = AutoConfig.from_pretrained(model_path)

deepspeed.init_distributed('nccl')
with deepspeed.OnDevice(dtype=torch.float16, device='meta'):
    model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.bfloat16)

model.eval()
model = deepspeed.init_inference(model,
    mp_size=args.world_size,
    dtype=torch.float16,
    checkpoint=os.path.join(model_path, 'ds_inference_config.json'),
    injection_policy={BloomBlock: ("self_attention.dense", "mlp.dense_4h_to_h")}
    base_dir=model_path
)
    args.model, 
    use_fast=False)

**Comment by lekurile** [comment] 2022-10-20 01:01
Hi @sunyt32,

Regarding the missing `checkpoint_engine` argument in the `get_sd_loader_json` function call, that's addressed in GH-2429.

> maybe the problem is deepspeed doesn't fully support replace_with_kernel_inject=False.

Yes, currently DeepSpeed only supports BLOOM with `replace_with_kernel_inject=True`.

May I ask the reason for running BLOOM with `replace_with_kernel_inject=False`, since kernel injection will give better performance?

Thanks,
Lev

**Comment by sunyt32** [comment] 2022-10-20 04:42
Hi @lekurile,
We tried to run experiments with the modified attention kernel in inference. To speed up, using DeepSpeed is a good choice for us.  Since it only supports common usage, we finished the experiments with naive pytorch anyway.
You can close this issue if you have no plan to support flexible BLOOM usage recently.

**Closed** 2022-10-20 04:52 UTC
Labels: bug, inference
